subdir-ccflags-y += -I$(srctree)/drivers/staging/lustre/include/
subdir-ccflags-y += -I$(srctree)/drivers/staging/lustre/lustre/include/

obj-$(CONFIG_LNET)		+= lnet/
obj-$(CONFIG_LUSTRE_FS)		+= lustre/
