/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 */
#ifndef __MTK_GMAC_DESC_H__
#define __MTK_GMAC_DESC_H__

#include <linux/bitops.h>

/* Normal transmit descriptor defines (without split feature) */

#define GMAC_GET_REG_BITS_LE(var, pos, len) ({			\
	typeof(pos) _pos = (pos);					\
	typeof(len) _len = (len);					\
	typeof(var) _var = le32_to_cpu((var));				\
	((_var) & GENMASK(_pos + _len - 1, _pos)) >> (_pos);		\
})

#define GMAC_SET_REG_BITS_LE(var, pos, len, val) ({			\
	typeof(var) _var = (var);					\
	typeof(pos) _pos = (pos);					\
	typeof(len) _len = (len);					\
	typeof(val) _val = (val);					\
	_val = (_val << _pos) & GENMASK(_pos + _len - 1, _pos);		\
	_var = (_var & ~GENMASK(_pos + _len - 1, _pos)) | _val;		\
	cpu_to_le32(_var);						\
})

#define TX_PACKET_ATTRIBUTES_CSUM_ENABLE_POS 0
#define TX_PACKET_ATTRIBUTES_CSUM_ENABLE_LEN 1
#define TX_PACKET_ATTRIBUTES_TSO_ENABLE_POS 1
#define TX_PACKET_ATTRIBUTES_TSO_ENABLE_LEN 1
#define TX_PACKET_ATTRIBUTES_VLAN_CTAG_POS 2
#define TX_PACKET_ATTRIBUTES_VLAN_CTAG_LEN 1
#define TX_PACKET_ATTRIBUTES_PTP_POS 3
#define TX_PACKET_ATTRIBUTES_PTP_LEN 1

#define TX_CONTEXT_DESC2_MSS_POS		0
#define TX_CONTEXT_DESC2_MSS_LEN		14
#define TX_CONTEXT_DESC3_CTXT_POS		30
#define TX_CONTEXT_DESC3_CTXT_LEN		1
#define TX_CONTEXT_DESC3_TCMSSV_POS		26
#define TX_CONTEXT_DESC3_TCMSSV_LEN		1
#define TX_CONTEXT_DESC3_VLTV_POS		16
#define TX_CONTEXT_DESC3_VLTV_LEN		1
#define TX_CONTEXT_DESC3_VT_POS			0
#define TX_CONTEXT_DESC3_VT_LEN			16

#define TX_NORMAL_DESC2_HL_B1L_POS		0
#define TX_NORMAL_DESC2_HL_B1L_LEN		14
#define TX_NORMAL_DESC2_IC_POS			31
#define TX_NORMAL_DESC2_IC_LEN			1
#define TX_NORMAL_DESC2_TTSE_POS		30
#define TX_NORMAL_DESC2_TTSE_LEN		1
#define TX_NORMAL_DESC2_VTIR_POS		14
#define TX_NORMAL_DESC2_VTIR_LEN		2
#define TX_NORMAL_DESC3_CIC_POS			16
#define TX_NORMAL_DESC3_CIC_LEN			2
#define TX_NORMAL_DESC3_CPC_POS			26
#define TX_NORMAL_DESC3_CPC_LEN			2
#define TX_NORMAL_DESC3_CTXT_POS		30
#define TX_NORMAL_DESC3_CTXT_LEN		1
#define TX_NORMAL_DESC3_FD_POS			29
#define TX_NORMAL_DESC3_FD_LEN			1
#define TX_NORMAL_DESC3_FL_POS			0
#define TX_NORMAL_DESC3_FL_LEN			15
#define TX_NORMAL_DESC3_LD_POS			28
#define TX_NORMAL_DESC3_LD_LEN			1
#define TX_NORMAL_DESC3_OWN_POS			31
#define TX_NORMAL_DESC3_OWN_LEN			1
#define TX_NORMAL_DESC3_TCPHDRLEN_POS		19
#define TX_NORMAL_DESC3_TCPHDRLEN_LEN		4
#define TX_NORMAL_DESC3_TCPPL_POS		0
#define TX_NORMAL_DESC3_TCPPL_LEN		18
#define TX_NORMAL_DESC3_TSE_POS			18
#define TX_NORMAL_DESC3_TSE_LEN			1
#define TX_NORMAL_DESC3_TTSS_POS		17
#define TX_NORMAL_DESC3_TTSS_LEN		1

#define TX_NORMAL_DESC2_VLAN_INSERT		0x2

#define RX_PACKET_ATTRIBUTES_CSUM_DONE_POS	0
#define RX_PACKET_ATTRIBUTES_CSUM_DONE_LEN	1
#define RX_PACKET_ATTRIBUTES_VLAN_CTAG_POS	1
#define RX_PACKET_ATTRIBUTES_VLAN_CTAG_LEN	1
#define RX_PACKET_ATTRIBUTES_INCOMPLETE_POS	2
#define RX_PACKET_ATTRIBUTES_INCOMPLETE_LEN	1
#define RX_PACKET_ATTRIBUTES_CONTEXT_POS	3
#define RX_PACKET_ATTRIBUTES_CONTEXT_LEN	1
#define RX_PACKET_ATTRIBUTES_RX_TSTAMP_POS	4
#define RX_PACKET_ATTRIBUTES_RX_TSTAMP_LEN	1

#define RX_PACKET_ERRORS_CRC_POS		2
#define RX_PACKET_ERRORS_CRC_LEN		1
#define RX_PACKET_ERRORS_FRAME_POS		3
#define RX_PACKET_ERRORS_FRAME_LEN		1
#define RX_PACKET_ERRORS_LENGTH_POS		0
#define RX_PACKET_ERRORS_LENGTH_LEN		1
#define RX_PACKET_ERRORS_OVERRUN_POS		1
#define RX_PACKET_ERRORS_OVERRUN_LEN		1

#define RX_NORMAL_DESC0_OVT_POS			0
#define RX_NORMAL_DESC0_OVT_LEN			16
#define RX_NORMAL_DESC1_TSA_POS			14
#define RX_NORMAL_DESC1_TSA_LEN			1
#define RX_NORMAL_DESC1_IPHE_POS		3
#define RX_NORMAL_DESC1_IPHE_LEN		1
#define RX_NORMAL_DESC1_IPCB_POS		6
#define RX_NORMAL_DESC1_IPCB_LEN		1
#define RX_NORMAL_DESC1_IPCE_POS		7
#define RX_NORMAL_DESC1_IPCE_LEN		1
#define RX_NORMAL_DESC2_HL_POS			0
#define RX_NORMAL_DESC2_HL_LEN			10
#define RX_NORMAL_DESC3_CDA_POS			27
#define RX_NORMAL_DESC3_CDA_LEN			1
#define RX_NORMAL_DESC3_CTXT_POS		30
#define RX_NORMAL_DESC3_CTXT_LEN		1
#define RX_NORMAL_DESC3_ES_POS			15
#define RX_NORMAL_DESC3_ES_LEN			1
#define RX_NORMAL_DESC3_LT_POS			16
#define RX_NORMAL_DESC3_LT_LEN			3
#define RX_NORMAL_DESC3_FD_POS			29
#define RX_NORMAL_DESC3_FD_LEN			1
#define RX_NORMAL_DESC3_INTE_POS		30
#define RX_NORMAL_DESC3_INTE_LEN		1
#define RX_NORMAL_DESC3_BUF2V_POS		25
#define RX_NORMAL_DESC3_BUF2V_LEN		1
#define RX_NORMAL_DESC3_BUF1V_POS		24
#define RX_NORMAL_DESC3_BUF1V_LEN		1
#define RX_NORMAL_DESC3_L34T_POS		20
#define RX_NORMAL_DESC3_L34T_LEN		4
#define RX_NORMAL_DESC3_LD_POS			28
#define RX_NORMAL_DESC3_LD_LEN			1
#define RX_NORMAL_DESC3_OWN_POS			31
#define RX_NORMAL_DESC3_OWN_LEN			1
#define RX_NORMAL_DESC3_PL_POS			0
#define RX_NORMAL_DESC3_PL_LEN			15
#define RX_NORMAL_DESC3_RS2V_POS		27
#define RX_NORMAL_DESC3_RS2V_LEN		1
#define RX_NORMAL_DESC3_RS1V_POS		26
#define RX_NORMAL_DESC3_RS1V_LEN		1
#define RX_NORMAL_DESC3_RS0V_POS		25
#define RX_NORMAL_DESC3_RS0V_LEN		1

#define RX_CONTEXT_DESC3_OWN_POS		31
#define RX_CONTEXT_DESC3_OWN_LEN		1
#define RX_CONTEXT_DESC3_CTXT_POS		30
#define RX_CONTEXT_DESC3_CTXT_LEN		1

#endif /* __MT2712_DESCS_H__ */

