obj-y += ccu_common.o
obj-y += ccu_reset.o

obj-y += ccu_frac.o

obj-y += ccu_div.o
obj-y += ccu_fixed_factor.o
obj-y += ccu_gate.o
obj-y += ccu_mp.o
obj-y += ccu_mux.o
obj-y += ccu_nk.o
obj-y += ccu_phase.o
