# Makefile for Qualcomm vidc driver

vidc-objs += \
		core.o \
		int_bufs.o \
		helpers.o \
		vdec.o \
		vdec_ctrls.o \
		venc.o \
		venc_ctrls.o \
		mem.o \
		resources.o \
		load.o \
		hfi_venus.o \
		hfi_msgs.o \
		hfi_cmds.o \
		hfi.o \

obj-$(CONFIG_QCOM_VIDC) += vidc.o
