obj-$(CONFIG_VIDEO_ROCKCHIP_VPU) += rockchip-vpu.o

rockchip-vpu-y += rockchip_vpu_drv.o \
		rockchip_vpu_enc.o \
		rk3288_vpu_hw.o \
		rk3288_vpu_hw_jpege.o \
		rk3399_vpu_hw.o \
		rk3399_vpu_hw_jpege.o
