# SPDX-License-Identifier: GPL-2.0
# Copyright (c)  2018 Intel Corporation

#
# Intel(R) I225-LM/I225-V 2.5G Ethernet Controller
#

obj-$(CONFIG_IGC) += igc.o

igc-objs := igc_main.o e1000_mac.o e1000_i225.o e1000_base.o
