obj-$(CONFIG_PHY_QCOM_APQ8064_SATA)	+= phy-qcom-apq8064-sata.o
obj-$(CONFIG_PHY_QCOM_IPQ806X_SATA)	+= phy-qcom-ipq806x-sata.o
obj-$(CONFIG_PHY_QCOM_UFS)		+= phy-qcom-ufs.o \
					+= phy-qcom-ufs-qmp-20nm.o \
					+= phy-qcom-ufs-qmp-14nm.o
