# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

generic-y += bpf_perf_event.h
generic-y += ipcbuf.h
generated-y += unistd_32.h
generated-y += unistd_64.h
generated-y += unistd_n32.h