obj-$(CONFIG_INFINIBAND_RDMAVT) += rdmavt.o

rdmavt-y := \
	rvt.o \
	rvt_comp.o \
	rvt_req.o \
	rvt_resp.o \
	rvt_recv.o \
	rvt_pool.o \
	rvt_queue.o \
	rvt_verbs.o \
	rvt_av.o \
	rvt_srq.o \
	rvt_qp.o \
	rvt_cq.o \
	rvt_mr.o \
	rvt_dma.o \
	rvt_opcode.o \
	rvt_mmap.o \
	rvt_mcast.o \
	rvt_icrc.o \
	rvt_task.o
