/*
 * Copyright (c) 2015 Mellanox Technologies Ltd. All rights reserved.
 * Copyright (c) 2015 System Fabric Works, Inc. All rights reserved.
 *
 * This software is available to you under a choice of one of two
 * licenses.  You may choose to be licensed under the terms of the GNU
 * General Public License (GPL) Version 2, available from the file
 * COPYING in the main directory of this source tree, or the
 * OpenIB.org BSD license below:
 *
 *     Redistribution and use in source and binary forms, with or
 *     without modification, are permitted provided that the following
 *     conditions are met:
 *
 *	- Redistributions of source code must retain the above
 *	  copyright notice, this list of conditions and the following
 *	  disclaimer.
 *
 *	- Redistributions in binary form must reproduce the above
 *	  copyright notice, this list of conditions and the following
 *	  disclaimer in the documentation and/or other materials
 *	  provided with the distribution.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <rdma/ib_pack.h>
#include "rvt_opcode.h"
#include "rvt_hdr.h"

/* useful information about work request opcodes and pkt opcodes in
 * table form
 */
struct rvt_wr_opcode_info rvt_wr_opcode_info[] = {
	[IB_WR_RDMA_WRITE]				= {
		.name	= "IB_WR_RDMA_WRITE",
		.mask	= {
			[IB_QPT_RC]	= WR_INLINE_MASK | WR_WRITE_MASK,
			[IB_QPT_UC]	= WR_INLINE_MASK | WR_WRITE_MASK,
		},
	},
	[IB_WR_RDMA_WRITE_WITH_IMM]			= {
		.name	= "IB_WR_RDMA_WRITE_WITH_IMM",
		.mask	= {
			[IB_QPT_RC]	= WR_INLINE_MASK | WR_WRITE_MASK,
			[IB_QPT_UC]	= WR_INLINE_MASK | WR_WRITE_MASK,
		},
	},
	[IB_WR_SEND]					= {
		.name	= "IB_WR_SEND",
		.mask	= {
			[IB_QPT_SMI]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_GSI]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_RC]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_UC]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_UD]	= WR_INLINE_MASK | WR_SEND_MASK,
		},
	},
	[IB_WR_SEND_WITH_IMM]				= {
		.name	= "IB_WR_SEND_WITH_IMM",
		.mask	= {
			[IB_QPT_SMI]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_GSI]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_RC]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_UC]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_UD]	= WR_INLINE_MASK | WR_SEND_MASK,
		},
	},
	[IB_WR_RDMA_READ]				= {
		.name	= "IB_WR_RDMA_READ",
		.mask	= {
			[IB_QPT_RC]	= WR_READ_MASK,
		},
	},
	[IB_WR_ATOMIC_CMP_AND_SWP]			= {
		.name	= "IB_WR_ATOMIC_CMP_AND_SWP",
		.mask	= {
			[IB_QPT_RC]	= WR_ATOMIC_MASK,
		},
	},
	[IB_WR_ATOMIC_FETCH_AND_ADD]			= {
		.name	= "IB_WR_ATOMIC_FETCH_AND_ADD",
		.mask	= {
			[IB_QPT_RC]	= WR_ATOMIC_MASK,
		},
	},
	[IB_WR_LSO]					= {
		.name	= "IB_WR_LSO",
		.mask	= {
			/* not supported */
		},
	},
	[IB_WR_SEND_WITH_INV]				= {
		.name	= "IB_WR_SEND_WITH_INV",
		.mask	= {
			[IB_QPT_RC]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_UC]	= WR_INLINE_MASK | WR_SEND_MASK,
			[IB_QPT_UD]	= WR_INLINE_MASK | WR_SEND_MASK,
		},
	},
	[IB_WR_RDMA_READ_WITH_INV]			= {
		.name	= "IB_WR_RDMA_READ_WITH_INV",
		.mask	= {
			[IB_QPT_RC]	= WR_READ_MASK,
		},
	},
	[IB_WR_LOCAL_INV]				= {
		.name	= "IB_WR_LOCAL_INV",
		.mask	= {
			/* not supported */
		},
	},
};

struct rvt_opcode_info rvt_opcode[RVT_NUM_OPCODE] = {
	[IB_OPCODE_RC_SEND_FIRST]			= {
		.name	= "IB_OPCODE_RC_SEND_FIRST",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_RWR_MASK
				| RVT_SEND_MASK | RVT_START_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_MIDDLE]		= {
		.name	= "IB_OPCODE_RC_SEND_MIDDLE]",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_SEND_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_LAST]			= {
		.name	= "IB_OPCODE_RC_SEND_LAST",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_COMP_MASK
				| RVT_SEND_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_LAST_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RC_SEND_LAST_WITH_IMMEDIATE",
		.mask	= RVT_IMMDT_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_SEND_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IMMDT]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_ONLY]			= {
		.name	= "IB_OPCODE_RC_SEND_ONLY",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_COMP_MASK
				| RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RC_SEND_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_IMMDT_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IMMDT]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_WRITE_FIRST]		= {
		.name	= "IB_OPCODE_RC_RDMA_WRITE_FIRST",
		.mask	= RVT_RETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_START_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_WRITE_MIDDLE]		= {
		.name	= "IB_OPCODE_RC_RDMA_WRITE_MIDDLE",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_WRITE_LAST]			= {
		.name	= "IB_OPCODE_RC_RDMA_WRITE_LAST",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_WRITE_LAST_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RC_RDMA_WRITE_LAST_WITH_IMMEDIATE",
		.mask	= RVT_IMMDT_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IMMDT]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_WRITE_ONLY]			= {
		.name	= "IB_OPCODE_RC_RDMA_WRITE_ONLY",
		.mask	= RVT_RETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_START_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_WRITE_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RC_RDMA_WRITE_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_RETH_MASK | RVT_IMMDT_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_READ_REQUEST]			= {
		.name	= "IB_OPCODE_RC_RDMA_READ_REQUEST",
		.mask	= RVT_RETH_MASK | RVT_REQ_MASK | RVT_READ_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_READ_RESPONSE_FIRST]		= {
		.name	= "IB_OPCODE_RC_RDMA_READ_RESPONSE_FIRST",
		.mask	= RVT_AETH_MASK | RVT_PAYLOAD_MASK | RVT_ACK_MASK
				| RVT_START_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_AETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_READ_RESPONSE_MIDDLE]		= {
		.name	= "IB_OPCODE_RC_RDMA_READ_RESPONSE_MIDDLE",
		.mask	= RVT_PAYLOAD_MASK | RVT_ACK_MASK | RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_READ_RESPONSE_LAST]		= {
		.name	= "IB_OPCODE_RC_RDMA_READ_RESPONSE_LAST",
		.mask	= RVT_AETH_MASK | RVT_PAYLOAD_MASK | RVT_ACK_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_AETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RC_RDMA_READ_RESPONSE_ONLY]		= {
		.name	= "IB_OPCODE_RC_RDMA_READ_RESPONSE_ONLY",
		.mask	= RVT_AETH_MASK | RVT_PAYLOAD_MASK | RVT_ACK_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_AETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RC_ACKNOWLEDGE]			= {
		.name	= "IB_OPCODE_RC_ACKNOWLEDGE",
		.mask	= RVT_AETH_MASK | RVT_ACK_MASK | RVT_START_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_AETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RC_ATOMIC_ACKNOWLEDGE]			= {
		.name	= "IB_OPCODE_RC_ATOMIC_ACKNOWLEDGE",
		.mask	= RVT_AETH_MASK | RVT_ATMACK_MASK | RVT_ACK_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_ATMACK_BYTES + RVT_AETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_AETH]	= RVT_BTH_BYTES,
			[RVT_ATMACK]	= RVT_BTH_BYTES
						+ RVT_AETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
					+ RVT_ATMACK_BYTES + RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RC_COMPARE_SWAP]			= {
		.name	= "IB_OPCODE_RC_COMPARE_SWAP",
		.mask	= RVT_ATMETH_MASK | RVT_REQ_MASK | RVT_ATOMIC_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_ATMETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_ATMETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_ATMETH_BYTES,
		}
	},
	[IB_OPCODE_RC_FETCH_ADD]			= {
		.name	= "IB_OPCODE_RC_FETCH_ADD",
		.mask	= RVT_ATMETH_MASK | RVT_REQ_MASK | RVT_ATOMIC_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_ATMETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_ATMETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_ATMETH_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_LAST_INV]		= {
		.name	= "IB_OPCODE_RC_SEND_LAST_INV",
		.mask	= RVT_IETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_SEND_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IETH_BYTES,
		}
	},
	[IB_OPCODE_RC_SEND_ONLY_INV]		= {
		.name	= "IB_OPCODE_RC_SEND_ONLY_INV",
		.mask	= RVT_IETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IETH_BYTES,
		}
	},

	/* UC */
	[IB_OPCODE_UC_SEND_FIRST]			= {
		.name	= "IB_OPCODE_UC_SEND_FIRST",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_RWR_MASK
				| RVT_SEND_MASK | RVT_START_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_UC_SEND_MIDDLE]		= {
		.name	= "IB_OPCODE_UC_SEND_MIDDLE",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_SEND_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_UC_SEND_LAST]			= {
		.name	= "IB_OPCODE_UC_SEND_LAST",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_COMP_MASK
				| RVT_SEND_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_UC_SEND_LAST_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_UC_SEND_LAST_WITH_IMMEDIATE",
		.mask	= RVT_IMMDT_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_SEND_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IMMDT]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_UC_SEND_ONLY]			= {
		.name	= "IB_OPCODE_UC_SEND_ONLY",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_COMP_MASK
				| RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_UC_SEND_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_UC_SEND_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_IMMDT_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IMMDT]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_UC_RDMA_WRITE_FIRST]		= {
		.name	= "IB_OPCODE_UC_RDMA_WRITE_FIRST",
		.mask	= RVT_RETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_START_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_UC_RDMA_WRITE_MIDDLE]		= {
		.name	= "IB_OPCODE_UC_RDMA_WRITE_MIDDLE",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_UC_RDMA_WRITE_LAST]			= {
		.name	= "IB_OPCODE_UC_RDMA_WRITE_LAST",
		.mask	= RVT_PAYLOAD_MASK | RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES,
		}
	},
	[IB_OPCODE_UC_RDMA_WRITE_LAST_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_UC_RDMA_WRITE_LAST_WITH_IMMEDIATE",
		.mask	= RVT_IMMDT_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_IMMDT]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_UC_RDMA_WRITE_ONLY]			= {
		.name	= "IB_OPCODE_UC_RDMA_WRITE_ONLY",
		.mask	= RVT_RETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_START_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_UC_RDMA_WRITE_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_UC_RDMA_WRITE_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_RETH_MASK | RVT_IMMDT_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_RETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RETH]	= RVT_BTH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},

	/* RD */
	[IB_OPCODE_RD_SEND_FIRST]			= {
		.name	= "IB_OPCODE_RD_SEND_FIRST",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_RD_SEND_MIDDLE]		= {
		.name	= "IB_OPCODE_RD_SEND_MIDDLE",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_SEND_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_RD_SEND_LAST]			= {
		.name	= "IB_OPCODE_RD_SEND_LAST",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_COMP_MASK | RVT_SEND_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_RD_SEND_LAST_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RD_SEND_LAST_WITH_IMMEDIATE",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_IMMDT_MASK
				| RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_SEND_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RD_SEND_ONLY]			= {
		.name	= "IB_OPCODE_RD_SEND_ONLY",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_SEND_MASK | RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_RD_SEND_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RD_SEND_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_IMMDT_MASK
				| RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_WRITE_FIRST]		= {
		.name	= "IB_OPCODE_RD_RDMA_WRITE_FIRST",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_RETH_MASK
				| RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_START_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_RETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_WRITE_MIDDLE]		= {
		.name	= "IB_OPCODE_RD_RDMA_WRITE_MIDDLE",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_WRITE_LAST]			= {
		.name	= "IB_OPCODE_RD_RDMA_WRITE_LAST",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_WRITE_LAST_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RD_RDMA_WRITE_LAST_WITH_IMMEDIATE",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_IMMDT_MASK
				| RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_WRITE_ONLY]			= {
		.name	= "IB_OPCODE_RD_RDMA_WRITE_ONLY",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_RETH_MASK
				| RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_WRITE_MASK | RVT_START_MASK
				| RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_RETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_RETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_WRITE_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_RD_RDMA_WRITE_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_RETH_MASK
				| RVT_IMMDT_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_WRITE_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_RETH_BYTES
				+ RVT_DETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_RETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_RETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_RETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_READ_REQUEST]			= {
		.name	= "IB_OPCODE_RD_RDMA_READ_REQUEST",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_RETH_MASK
				| RVT_REQ_MASK | RVT_READ_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_RETH_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_RETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RETH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_RDETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_READ_RESPONSE_FIRST]		= {
		.name	= "IB_OPCODE_RD_RDMA_READ_RESPONSE_FIRST",
		.mask	= RVT_RDETH_MASK | RVT_AETH_MASK
				| RVT_PAYLOAD_MASK | RVT_ACK_MASK
				| RVT_START_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_AETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_READ_RESPONSE_MIDDLE]		= {
		.name	= "IB_OPCODE_RD_RDMA_READ_RESPONSE_MIDDLE",
		.mask	= RVT_RDETH_MASK | RVT_PAYLOAD_MASK | RVT_ACK_MASK
				| RVT_MIDDLE_MASK,
		.length = RVT_BTH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_READ_RESPONSE_LAST]		= {
		.name	= "IB_OPCODE_RD_RDMA_READ_RESPONSE_LAST",
		.mask	= RVT_RDETH_MASK | RVT_AETH_MASK | RVT_PAYLOAD_MASK
				| RVT_ACK_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_AETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RD_RDMA_READ_RESPONSE_ONLY]		= {
		.name	= "IB_OPCODE_RD_RDMA_READ_RESPONSE_ONLY",
		.mask	= RVT_RDETH_MASK | RVT_AETH_MASK | RVT_PAYLOAD_MASK
				| RVT_ACK_MASK | RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_AETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RD_ACKNOWLEDGE]			= {
		.name	= "IB_OPCODE_RD_ACKNOWLEDGE",
		.mask	= RVT_RDETH_MASK | RVT_AETH_MASK | RVT_ACK_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_AETH_BYTES + RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_AETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
		}
	},
	[IB_OPCODE_RD_ATOMIC_ACKNOWLEDGE]			= {
		.name	= "IB_OPCODE_RD_ATOMIC_ACKNOWLEDGE",
		.mask	= RVT_RDETH_MASK | RVT_AETH_MASK | RVT_ATMACK_MASK
				| RVT_ACK_MASK | RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_ATMACK_BYTES + RVT_AETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_AETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_ATMACK]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_AETH_BYTES,
		}
	},
	[IB_OPCODE_RD_COMPARE_SWAP]			= {
		.name	= "RD_COMPARE_SWAP",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_ATMETH_MASK
				| RVT_REQ_MASK | RVT_ATOMIC_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_ATMETH_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_ATMETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES +
						+ RVT_ATMETH_BYTES
						+ RVT_DETH_BYTES +
						+ RVT_RDETH_BYTES,
		}
	},
	[IB_OPCODE_RD_FETCH_ADD]			= {
		.name	= "IB_OPCODE_RD_FETCH_ADD",
		.mask	= RVT_RDETH_MASK | RVT_DETH_MASK | RVT_ATMETH_MASK
				| RVT_REQ_MASK | RVT_ATOMIC_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_ATMETH_BYTES + RVT_DETH_BYTES
				+ RVT_RDETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_RDETH]	= RVT_BTH_BYTES,
			[RVT_DETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES,
			[RVT_ATMETH]	= RVT_BTH_BYTES
						+ RVT_RDETH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES +
						+ RVT_ATMETH_BYTES
						+ RVT_DETH_BYTES +
						+ RVT_RDETH_BYTES,
		}
	},

	/* UD */
	[IB_OPCODE_UD_SEND_ONLY]			= {
		.name	= "IB_OPCODE_UD_SEND_ONLY",
		.mask	= RVT_DETH_MASK | RVT_PAYLOAD_MASK | RVT_REQ_MASK
				| RVT_COMP_MASK | RVT_RWR_MASK | RVT_SEND_MASK
				| RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_DETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_DETH]	= RVT_BTH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_DETH_BYTES,
		}
	},
	[IB_OPCODE_UD_SEND_ONLY_WITH_IMMEDIATE]		= {
		.name	= "IB_OPCODE_UD_SEND_ONLY_WITH_IMMEDIATE",
		.mask	= RVT_DETH_MASK | RVT_IMMDT_MASK | RVT_PAYLOAD_MASK
				| RVT_REQ_MASK | RVT_COMP_MASK | RVT_RWR_MASK
				| RVT_SEND_MASK | RVT_START_MASK | RVT_END_MASK,
		.length = RVT_BTH_BYTES + RVT_IMMDT_BYTES + RVT_DETH_BYTES,
		.offset = {
			[RVT_BTH]	= 0,
			[RVT_DETH]	= RVT_BTH_BYTES,
			[RVT_IMMDT]	= RVT_BTH_BYTES
						+ RVT_DETH_BYTES,
			[RVT_PAYLOAD]	= RVT_BTH_BYTES
						+ RVT_DETH_BYTES
						+ RVT_IMMDT_BYTES,
		}
	},

};
