# SPDX-License-Identifier: GPL-2.0 OR BSD-2-Clause
#
# Makefile for Amazon Elastic Fabric Adapter (EFA) device drivers.
#

obj-$(CONFIG_INFINIBAND_EFA) += efa.o

efa-y := efa_bitmap.o efa_com_cmd.o efa_com.o efa_main.o efa_verbs.o
