#
# Tegra thermal specific Makefile
#

# Tegra soc thermal drivers
obj-$(CONFIG_TEGRA_SOCTHERM)	+= tegra_soctherm.o tegra_soctherm_fuse.o
obj-$(CONFIG_TEGRA124_SOCTHERM)	+= tegra124_soctherm.o
obj-$(CONFIG_TEGRA210_SOCTHERM)	+= tegra210_soctherm.o
