vfio-platform-calxedaxgmac-y := vfio_platform_calxedaxgmac.o

ccflags-y += -Idrivers/vfio/platform -Idrivers/vfio/platform/reset

obj-$(CONFIG_VFIO_PLATFORM_CALXEDAXGMAC_RESET) += vfio-platform-calxedaxgmac.o
