
ccflags-y := -Idrivers/net/ethernet/broadcom/bnxt
obj-$(CONFIG_INFINIBAND_BNXTRE) += bnxt_re.o
bnxt_re-y := bnxt_re_main.o bnxt_re_ib_verbs.o bnxt_re_debugfs.o \
	     bnxt_qplib_res.o bnxt_qplib_rcfw.o	\
	     bnxt_qplib_sp.o bnxt_qplib_fp.o
