# SPDX-License-Identifier: (GPL-2.0 OR MIT)
#
# Microsemi MIPS SoC support
#
# License: Dual MIT/GPL
# Copyright (c) 2017 Microsemi Corporation

#
# Makefile for the Microsemi MIPS SoCs
#
obj-y := setup.o
