#!/bin/sh

# pstore_post_reboot_tests - Check pstore's behavior after crash/reboot
#
# Copyright (C) Hitachi Ltd., 2015
#  Written by Hiraku Toyooka <hiraku.toyooka.gu@hitachi.com>
#
# Released under the terms of the GPL v2.

. ./common_tests

if [ -e $REBOOT_FLAG  ]; then
    rm $REBOOT_FLAG
else
    prlog "pstore_crash_test has not been executed yet. we skip further tests."
    exit 0
fi

prlog -n "Mounting pstore filesystem ... "
mount_info=`grep pstore /proc/mounts`
if [ $? -eq 0 ]; then
    mount_point=`echo ${mount_info} | cut -d' ' -f2 | head -n1`
    prlog "ok"
else
    mount none /sys/fs/pstore -t pstore
    if [ $? -eq 0 ]; then
	mount_point=`grep pstore /proc/mounts | cut -d' ' -f2 | head -n1`
	prlog "ok"
    else
	prlog "FAIL"
	exit 1
    fi
fi

cd ${mount_point}

prlog -n "Checking dmesg files exist in pstore filesystem ... "
check_files_exist dmesg-${backend}-

prlog -n "Checking console files exist in pstore filesystem ... "
check_files_exist console-${backend}-

prlog -n "Checking pmsg files exist in pstore filesystem ... "
check_files_exist pmsg-${backend}-

prlog -n "Checking dmesg files contain oops end marker"
grep_end_trace() {
    grep -q "\---\[ end trace" $1
}
files=`ls dmesg-${backend}-*`
operate_files $? "$files" grep_end_trace

prlog -n "Checking console file contains oops end marker ... "
grep -q "\---\[ end trace" console-${backend}-0
show_result $?

prlog -n "Checking pmsg-"${backend}"-0 properly keeps the content written before crash ... "
check_pmsg_content pmsg-${backend}-0

prlog -n "Checking the last pmsg area is detected "
last_num_pmsg=`ls -v pmsg-* | tail -n1 | sed -e "s/^pmsg-${backend}-\([0-9]*\).*$/\1/"`
last_num_devpmsg=`ls -v /dev/pmsg* | tail -n1 | sed -e "s/^\/dev\/pmsg\([0-9]*\).*$/\1/"`
#checks the last number of pmsg-*-* and /dev/pmsg* correspond.
if [ "$last_num_pmsg" -eq "$last_num_devpmsg" ]; then
    if [ "$last_num_pmsg" = "0" ]; then
	prlog "... No multiple pmsg-*-* exists. We skip this testcase."
    else
	prlog -n "(pmsg-${backend}-${last_num_pmsg}) ... "
	check_pmsg_content pmsg-${backend}-${last_num_pmsg}
    fi
else
    prlog "FAIL"
    rc=1
fi

prlog -n "Removing all files in pstore filesystem "
files=`ls *-${backend}-*`
operate_files $? "$files" rm

exit $rc
