#!/bin/sh

# pstore_tests - Check pstore's behavior before crash/reboot
#
# Copyright (C) Hitachi Ltd., 2015
#  Written by Hiraku Toyooka <hiraku.toyooka.gu@hitachi.com>
#
# Released under the terms of the GPL v2.

. ./common_tests

prlog -n "Checking pstore console is registered ... "
dmesg | grep -q "console \[pstore"
show_result $?

prlog -n "Checking /dev/pmsg files exist ... "
check_files_exist /dev/pmsg

prlog -n "Writing unique string to /dev/pmsg0 ... "
if [ -e "/dev/pmsg0" ]; then
    echo "${TEST_STRING_PATTERN}""$UUID" > /dev/pmsg0
    show_result $?
    echo "$UUID" > $TOP_DIR/uuid
else
    prlog "FAIL"
    rc=1
fi

last_devpmsg=`ls -v /dev/pmsg* | tail -n1`
prlog -n "Writing unique string to the last /dev/pmsgN "
if [ "$last_devpmsg" = "/dev/pmsg0" ]; then
    prlog "... No multiple /dev/pmsg* exists. We skip this testcase."
else
    prlog -n "(${last_devpmsg}) ... "
    echo "${TEST_STRING_PATTERN}""$UUID" > ${last_devpmsg}
    show_result $?

fi

exit $rc
