obj-y += berlin2-avpll.o berlin2-pll.o berlin2-div.o
obj-y += pll.o clk.o gate.o clk-berlin4ct.o
obj-$(CONFIG_MACH_BERLIN_BG2)	+= bg2.o
obj-$(CONFIG_MACH_BERLIN_BG2CD)	+= bg2.o
obj-$(CONFIG_MACH_BERLIN_BG2Q)	+= bg2q.o
