/* SPDX-License-Identifier: GPL-2.0 */
/* Octeon III Packet-Output Processing Unit (PKO)
 *
 * Copyright (C) 2018 Cavium, Inc.
 */
#ifndef _OCTEON3_PKO_H_
#define _OCTEON3_PKO_H_

#include <linux/bitops.h>

#define PKO_DPFI_ENA_ENABLE			BIT(0)
#define PKO_DPFI_FLUSH_FLUSH_EN			BIT(0)
#define PKO_DPFI_FPA_AURA_NODE_SHIFT		10
#define PKO_DPFI_STATUS_CACHE_FLUSHED		BIT(0)
#define PKO_DQ_SCHEDULE_PRIO_SHIFT		24
#define PKO_DQ_SW_XOFF_SC_RAM_FLIP		BIT(2)
#define PKO_DQ_SW_XOFF_SC_RAM_CDIS		BIT(1)
#define PKO_DQ_TOPOLOGY_PARENT_MASK		GENMASK_ULL(25, 16)
#define PKO_DQ_TOPOLOGY_PARENT_SHIFT		16
#define PKO_DQ_WM_CTL_KIND			BIT(49)
#define PKO_ENABLE_ENABLE			BIT(0)
#define PKO_L12_SQ_TOPOLOGY_PRIO_ANCHOR_MASK	GENMASK_ULL(40, 32)
#define PKO_L1_SQ_LINK_LINK_SHIFT		44
#define PKO_L1_SQ_SHAPE_LINK_SHIFT		13
#define PKO_L2_DQ_TOPOLOGY_PARENT_MASK		GENMASK_ULL(20, 16)
#define PKO_L1_SQ_TOPOLOGY_LINK_SHIFT		16
#define PKO_L345_SQ_TOPOLOGY_PRIO_ANCHOR_MASK	GENMASK_ULL(41, 32)
#define PKO_L34_DQ_TOPOLOGY_PARENT_MASK		GENMASK_ULL(24, 16)
#define PKO_L3_L2_CHANNEL_CC_CHANNEL_MASK	GENMASK_ULL(43, 32)
#define PKO_L3_L2_CHANNEL_CC_CHANNEL_SHIFT	32
#define PKO_LUT_PORT_MASK			0xf00
#define PKO_LUT_PORT_TO_INDEX			0x800
#define PKO_LUT_PQ_IDX_SHIFT			9
#define PKO_LUT_QUEUE_NUMBER_MASK		GENMASK_ULL(7, 0)
#define PKO_LUT_QUEUE_NUMBER_SHIFT		8
#define PKO_LUT_VALID				BIT(15)
#define PKO_MAC_CFG_FCS_ENA			BIT(15)
#define PKO_MAC_CFG_FCS_SOP_OFF_MASK		GENMASK_ULL(14, 7)
#define PKO_MAC_CFG_FCS_SOP_OFF_SHIFT		7
#define PKO_MAC_CFG_FIFO_GRP_SHIFT		2
#define PKO_MAC_CFG_FIFO_NUM_MASK		GENMASK_ULL(4, 0)
#define PKO_MAC_CFG_FIFO_NUM_UNDEFINED		0x1f
#define PKO_MAC_CFG_FIFO_OFF_MASK		GENMASK_ULL(1, 0)
#define PKO_MAC_CFG_FIFO_UNDEFINED		0x1f
#define PKO_MAC_CFG_MIN_PAD_ENA			BIT(16)
#define PKO_MAC_CFG_SKID_MAX_CNT_MASK		GENMASK_ULL(6, 5)
#define PKO_PDM_DQ_MINPAD_MINPAD		BIT(0)
#define PKO_PDM_PAD_MINLEN_SHIFT		3
#define PKO_PDM_PAD_MINLEN_TYPICAL		60
#define PKO_PTF_IOBP_CFG_MAX_READ_SIZE_MASK	GENMASK_ULL(6, 0)
#define PKO_PTF_STATUS_IN_FLIGHT_CNT_MASK	GENMASK_ULL(11, 5)
#define PKO_PTF_STATUS_MAC_NUM_MASK		GENMASK_ULL(4, 0)
#define PKO_PTGF_CFG_RATE_MASK			GENMASK_ULL(5, 3)
#define PKO_PTGF_CFG_RATE_SHIFT			3
#define PKO_PTGF_CFG_RESET			BIT(6)
#define PKO_PTGF_CFG_SIZE_MASK			GENMASK_ULL(2, 0)
#define PKO_QUERY_DMA_SCRADDR_SHIFT		56
#define PKO_QUERY_DMA_RTNLEN_SHIFT		48
#define PKO_QUERY_DMA_DID_SHIFT			40
#define PKO_QUERY_DMA_NODE_SHIFT		36
#define PKO_QUERY_DMA_DQOP_SHIFT		32
#define PKO_QUERY_DMA_DQ_SHIFT			16
#define PKO_QUERY_RTN_DEPTH_MASK		GENMASK_ULL(47, 0)
#define PKO_QUERY_RTN_DQSTATUS_MASK		GENMASK_ULL(63, 60)
#define PKO_QUERY_RTN_DQSTATUS_SHIFT		60

/* PKO_DQ_STATUS_E */
enum pko_dq_status_e {
	PKO_DQSTATUS_PASS = 0,
	PKO_DQSTATUS_BADSTATE = 8,
	PKO_DQSTATUS_NOFPABUF,
	PKO_DQSTATUS_NOPKOBUF,
	PKO_DQSTATUS_FAILRTNPTR,
	PKO_DQSTATUS_ALREADYCREATED,
	PKO_DQSTATUS_NOTCREATED,
	PKO_DQSTATUS_NOTEMPTY,
	PKO_DQSTATUS_SENDPKTDROP
};

#define PKO_SHAPER_CFG_COLOR_AWARE		BIT(1)
#define PKO_SQ_TOPOLOGY_LINK_SHIFT		16
#define PKO_SQ_TOPOLOGY_PRIO_ANCHOR_SHIFT	32
#define PKO_SQ_TOPOLOGY_RR_PRIO_MASK		GENMASK_ULL(4, 1)
#define PKO_SQ_TOPOLOGY_RR_PRIO_SHAPER		0xf
#define PKO_SQ_TOPOLOGY_RR_PRIO_SHIFT		1
#define PKO_STATUS_PKO_RDY			BIT(63)

#define PKO_SEND_HDR_AURA_SHIFT			48
#define PKO_SEND_HDR_CKL4_SHIFT			46
#define PKO_SEND_HDR_CKL3			BIT(45)
#define PKO_SEND_HDR_LE				BIT(43)
#define PKO_SEND_HDR_N2				BIT(42)
#define PKO_SEND_HDR_DF				BIT(40)
#define PKO_SEND_HDR_L4PTR_MASK			GENMASK_ULL(31, 24)
#define PKO_SEND_HDR_L4PTR_SHIFT		24
#define PKO_SEND_HDR_L3PTR_SHIFT		16

#define PKO_SEND_SUBDC4_SHIFT			44
#define PKO_SEND_EXT_RA_SHIFT			40
#define PKO_SEND_EXT_TSTMP			BIT(39)
#define PKO_SEND_EXT_MARKPTR_SHIFT		16

/* PKO_REDALG_E */
enum pko_redalg_e {
	PKO_REDALG_E_STD,
	PKO_REDALG_E_SEND,
	PKO_REDALG_E_STALL,
	PKO_REDALG_E_DISCARD
};

#define PKO_SEND_TSO_L2LEN_SHIFT		56
#define PKO_SEND_TSO_SB_SHIFT			24
#define PKO_SEND_TSO_MSS_SHIFT			8

#define PKO_SEND_MEM_WMEM_SHIFT			62
#define PKO_SEND_MEM_DSZ_SHIFT			60
#define PKO_SEND_MEM_ALG_SHIFT			56
#define PKO_SEND_MEM_OFFSET_SHIFT		48

/* PKO_MEMALG_E */
enum pko_memalg_e {
	PKO_MEMALG_SET = 0,
	PKO_MEMALG_SETTSTMP,
	PKO_MEMALG_SETRSLT,
	PKO_MEMALG_ADD = 8,
	PKO_MEMALG_SUB,
	PKO_MEMALG_ADDLEN,
	PKO_MEMALG_SUBLEN,
	PKO_MEMALG_ADDMBUF,
	PKO_MEMALG_SUBMBUF
};

/* PKO_MEMDSZ_E */
enum pko_memdsz_e {
	PKO_MEMDSZ_B64,
	PKO_MEMDSZ_B32,
	PKO_MEMDSZ_B16,
	PKO_MEMDSZ_B8
};

#define PKO_SEND_WORK_GRP_SHIFT			52
#define PKO_SEND_WORK_TT_SHIFT			50

#define PKO_SEND_GATHER_SIZE_MASK		GENMASK_ULL(63, 48)
#define PKO_SEND_GATHER_SIZE_SHIFT		48
#define PKO_SEND_GATHER_SUBDC_SHIFT		45
#define PKO_SEND_GATHER_ADDR_MASK		GENMASK_ULL(41, 0)

/* Pko sub-command three bit codes (SUBDC3) */
#define PKO_SENDSUBDC_GATHER			0x1

/* Pko sub-command four bit codes (SUBDC4) */
#define PKO_SENDSUBDC_TSO			0x8
#define PKO_SENDSUBDC_FREE			0x9
#define PKO_SENDSUBDC_WORK			0xa
#define PKO_SENDSUBDC_MEM			0xc
#define PKO_SENDSUBDC_EXT			0xd

#endif /* _OCTEON3_PKO_H_ */
