/* SPDX-License-Identifier: GPL-2.0 */
/* Octeon III Packet Input Unit (PKI)
 *
 * Copyright (C) 2018 Cavium, Inc.
 */
#ifndef _OCTEON3_PKI_H_
#define _OCTEON3_PKI_H_

#include <linux/bitops.h>

#define PKI_AURA_CFG_ENA_RED			BIT(18)

#define PKI_BUF_CTL_FPA_WAIT			BIT(10)
#define PKI_BUF_CTL_PKT_OFF			BIT(5)
#define PKI_BUF_CTL_PBP_EN			BIT(2)
#define PKI_BUF_CTL_PKI_EN			BIT(0)

#define PKI_CL_ECC_CTL_PCAM_EN			BIT(63)
#define PKI_CL_ECC_CTL_PCAM1_CDIS		BIT(4)
#define PKI_CL_ECC_CTL_PCAM0_CDIS		BIT(3)

#define PKI_CL_PCAM_ACTION_ADVANCE_4B		BIT(2)
#define PKI_CL_PCAM_ACTION_L2_CUSTOM		BIT(1)
#define PKI_CL_PCAM_ACTION_SETTY_SHIFT		8
#define PKI_CL_PCAM_MATCH_DATA1_SHIFT		32
#define PKI_CL_PCAM_TERM_VALID			BIT(63)
#define PKI_CL_PCAM_TERM_TERM1_SHIFT		40
#define PKI_CL_PCAM_TERM_STYLE1_SHIFT		32
#define PKI_CL_PCAM_TERM_TERM0_SHIFT		8

#define PKI_CL_PKIND_CFG_FCS_PRES		BIT(7)

#define PKI_CL_PKIND_SKIP_FCS_SKIP_MASK		GENMASK_ULL(15, 8)
#define PKI_CL_PKIND_SKIP_FCS_SKIP_SHIFT	8
#define PKI_CL_PKIND_SKIP_INST_SKIP_MASK	GENMASK_ULL(7, 0)

#define PKI_CL_PKIND_STYLE_PARSE_MODE_MASK	GENMASK_ULL(14, 8)
#define PKI_CL_PKIND_STYLE_STYLE_MASK		GENMASK_ULL(7, 0)

#define PKI_CL_STYLE_ALG_QPG_PORT_MSB_MASK	GENMASK_ULL(20, 17)
#define PKI_CL_STYLE_ALG_TT_SHIFT		30

#define PKI_CL_STYLE_CFG_LENERR_EN		BIT(29)
#define PKI_CL_STYLE_CFG_MAXERR_EN		BIT(26)
#define PKI_CL_STYLE_CFG_MINERR_EN		BIT(25)
#define PKI_CL_STYLE_CFG_FCS_STRIP		BIT(23)
#define PKI_CL_STYLE_CFG_FCS_CHK		BIT(22)

#define PKI_CL_STYLE_CFG2_LEN_TAG_SRC_LF	BIT(22)
#define PKI_CL_STYLE_CFG2_LEN_TAG_SRC_LE	BIT(21)
#define PKI_CL_STYLE_CFG2_LEN_TAG_SRC_LD	BIT(20)
#define PKI_CL_STYLE_CFG2_LEN_TAG_SRC_LC	BIT(19)
#define PKI_CL_STYLE_CFG2_LEN_TAG_DST_LF	BIT(16)
#define PKI_CL_STYLE_CFG2_LEN_TAG_DST_LE	BIT(15)
#define PKI_CL_STYLE_CFG2_LEN_TAG_DST_LD	BIT(14)
#define PKI_CL_STYLE_CFG2_LEN_TAG_DST_LC	BIT(13)
#define PKI_CL_STYLE_CFG2_LEN_LF		BIT(10)
#define PKI_CL_STYLE_CFG2_LEN_LC		BIT(7)
#define PKI_CL_STYLE_CFG2_CSUM_LF		BIT(4)
#define PKI_CL_STYLE_CFG2_CSUM_LE		BIT(3)
#define PKI_CL_STYLE_CFG2_CSUM_LD		BIT(2)
#define PKI_CL_STYLE_CFG2_CSUM_LC		BIT(1)

#define PKI_CL_STYLE_CFG2_CSUM_ALL	(PKI_CL_STYLE_CFG2_CSUM_LF |	       \
					 PKI_CL_STYLE_CFG2_CSUM_LE |	       \
					 PKI_CL_STYLE_CFG2_CSUM_LD |	       \
					 PKI_CL_STYLE_CFG2_CSUM_LC)

#define PKI_CL_STYLE_CFG2_LEN_TAG_ALL	(PKI_CL_STYLE_CFG2_LEN_TAG_DST_LF |    \
					 PKI_CL_STYLE_CFG2_LEN_TAG_DST_LE |    \
					 PKI_CL_STYLE_CFG2_LEN_TAG_DST_LD |    \
					 PKI_CL_STYLE_CFG2_LEN_TAG_DST_LC)

#define PKI_ICG_CFG_PENA			BIT(24)

#define PKI_LTYPE_MAP_BELTYPE_MASK		GENMASK_ULL(2, 0)

#define PKI_QPG_TBL_PADD_MASK			GENMASK_ULL(59, 48)
#define PKI_QPG_TBL_GRPTAG_OK_MASK		GENMASK_ULL(47, 45)
#define PKI_QPG_TBL_GRPTAG_OK_SHIFT		45
#define PKI_QPG_TBL_GRP_OK_MASK			GENMASK_ULL(41, 32)
#define PKI_QPG_TBL_GRP_OK_SHIFT		32
#define PKI_QPG_TBL_GRPTAG_BAD_MASK		GENMASK_ULL(31, 29)
#define PKI_QPG_TBL_GRPTAG_BAD_SHIFT		29
#define PKI_QPG_TBL_GRP_BAD_MASK		GENMASK_ULL(25, 16)
#define PKI_QPG_TBL_GRP_BAD_SHIFT		16
#define PKI_QPG_TBL_LAURA_MASK			GENMASK_ULL(9, 0)
#define PKI_QPG_TBL_GRP_NUM_BITS_SHIFT		8

#define PKI_SFT_RST_BUSY			BIT(63)
#define PKI_SFT_RST_ACTIVE			BIT(32)
#define PKI_SFT_RST_RST				BIT(0)

#define PKI_STYLE_BUF_WQE_SKIP_SHIFT	28
#define PKI_STYLE_BUF_FIRST_SKIP_SHIFT	22
#define PKI_STYLE_BUF_LATER_SKIP_SHIFT	16

/* Values for wqe word2 [ERRLEV] */
#define PKI_ERRLEV_LA		0x01

/* Values for wqe word2 [OPCODE] */
#define PKI_OPCODE_NONE		0x00
#define PKI_OPCODE_JABBER	0x02
#define PKI_OPCODE_FCS		0x07

/* Values for layer type in wqe */
#define PKI_LTYPE_IP4		0x08
#define PKI_LTYPE_IP6		0x0a
#define PKI_LTYPE_TCP		0x10
#define PKI_LTYPE_UDP		0x11
#define PKI_LTYPE_SCTP		0x12

#endif /* _OCTEON3_PKI_H_ */
