/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2018 Zodiac Inflight Innovations
 *
 * Author: Andrey Smirnov <andrew.smirnov@gmail.com>
 */

#ifndef DT_BINDING_RESET_IMX8M_H
#define DT_BINDING_RESET_IMX8M_H

#include "imx7-reset.h"

#define IMX8M_RESET_A53_CORE_POR_RESET0 IMX7_RESET_A7_CORE_POR_RESET0
#define IMX8M_RESET_A53_CORE_POR_RESET1 IMX7_RESET_A7_CORE_POR_RESET1

#define IMX8M_RESET_A53_CORE_RESET0     IMX7_RESET_A7_CORE_RESET0
#define IMX8M_RESET_A53_CORE_RESET1     IMX7_RESET_A7_CORE_RESET1

#define IMX8M_RESET_A53_DBG_RESET0	IMX7_RESET_A7_DBG_RESET0
#define IMX8M_RESET_A53_DBG_RESET1	IMX7_RESET_A7_DBG_RESET1

#define IMX8M_RESET_A53_ETM_RESET0	IMX7_RESET_A7_ETM_RESET0
#define IMX8M_RESET_A53_ETM_RESET1	IMX7_RESET_A7_ETM_RESET1

#define IMX8M_RESET_A53_SOC_DBG_RESET   IMX7_RESET_A7_SOC_DBG_RESET
#define IMX8M_RESET_A53_L2RESET         IMX7_RESET_A7_L2RESET
#define IMX8M_RESET_SW_M4C_RST          IMX7_RESET_SW_M4C_RST
#define IMX8M_RESET_SW_M4P_RST          IMX7_RESET_SW_M4P_RST
#define IMX8M_RESET_EIM_RST             IMX7_RESET_EIM_RST
#define IMX8M_RESET_HSICPHY_PORT_RST    IMX7_RESET_HSICPHY_PORT_RST
#define IMX8M_RESET_USBPHY1_POR         IMX7_RESET_USBPHY1_POR
#define IMX8M_RESET_USBPHY1_PORT_RST    IMX7_RESET_USBPHY1_PORT_RST
#define IMX8M_RESET_USBPHY2_POR         IMX7_RESET_USBPHY2_POR
#define IMX8M_RESET_USBPHY2_PORT_RST    IMX7_RESET_USBPHY2_PORT_RST
#define IMX8M_RESET_MIPI_PHY_MRST       IMX7_RESET_MIPI_PHY_MRST
#define IMX8M_RESET_MIPI_PHY_SRST       IMX7_RESET_MIPI_PHY_SRST

#define IMX8M_RESET_PCIEPHY             IMX7_RESET_PCIEPHY
#define IMX8M_RESET_PCIEPHY_PERST	IMX7_RESET_PCIEPHY_PERST
#define IMX8M_RESET_PCIE_CTRL_APPS_EN   IMX7_RESET_PCIE_CTRL_APPS_EN
#define IMX8M_RESET_DDRC_PRST           IMX7_RESET_DDRC_PRST
#define IMX8M_RESET_DDRC_CORE_RST       IMX7_RESET_DDRC_CORE_RST

#define IMX8M_RESET_PCIE_CTRL_APPS_TURNOFF IMX7_RESET_PCIE_CTRL_APPS_TURNOFF
#define IMX8M_RESET_PCIE_CTRL_APPS_CLK_REQ IMX7_RESET_PCIE_CTRL_APPS_CLK_REQ

#endif
