obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += mtk_vcodec_intr.o \
				       mtk_vcodec_util.o \
				       mtk_vcodec_enc_drv.o \
				       mtk_vcodec_enc.o \
				       mtk_vcodec_enc_pm.o \
				       venc_drv_if.o

obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += vp8_enc/

ccflags-y += -I$(srctree)/drivers/media/platform/mtk-vpu
