obj-$(CONFIG_RDMA_SIW) += siw.o

siw-y := \
	siw_main.o \
	siw_cm.o \
	siw_verbs.o \
	siw_obj.o \
	siw_qp.o \
	siw_qp_tx.o \
	siw_qp_rx.o \
	siw_cq.o \
	siw_cm.o \
	siw_debug.o \
	siw_ae.o \
	siw_mem.o
