/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _ASM_MIPS_KVM_TYPES_H
#define _ASM_MIPS_KVM_TYPES_H

#define KVM_ARCH_WANT_MMU_MEMCACHE

#define KVM_MMU_NR_MEMCACHE_OBJS 4

#define KVM_MMU_CACHE_GFP	GFP_KERNEL
#define KVM_MMU_CACHE_PAGE_GFP	GFP_KERNEL

#endif /* _ASM_MIPS_KVM_TYPES_H */
