#ifndef _UAPI_ASM_POWERPC_PERF_REGS_H
#define _UAPI_ASM_POWERPC_PERF_REGS_H

enum perf_event_powerpc_regs {
	PERF_REG_POWERPC_R0,
	PERF_REG_POWERPC_R1,
	PERF_REG_POWERPC_R2,
	PERF_REG_POWERPC_R3,
	PERF_REG_POWERPC_R4,
	PERF_REG_POWERPC_R5,
	PERF_REG_POWERPC_R6,
	PERF_REG_POWERPC_R7,
	PERF_REG_POWERPC_R8,
	PERF_REG_POWERPC_R9,
	PERF_REG_POWERPC_R10,
	PERF_REG_POWERPC_R11,
	PERF_REG_POWERPC_R12,
	PERF_REG_POWERPC_R13,
	PERF_REG_POWERPC_R14,
	PERF_REG_POWERPC_R15,
	PERF_REG_POWERPC_R16,
	PERF_REG_POWERPC_R17,
	PERF_REG_POWERPC_R18,
	PERF_REG_POWERPC_R19,
	PERF_REG_POWERPC_R20,
	PERF_REG_POWERPC_R21,
	PERF_REG_POWERPC_R22,
	PERF_REG_POWERPC_R23,
	PERF_REG_POWERPC_R24,
	PERF_REG_POWERPC_R25,
	PERF_REG_POWERPC_R26,
	PERF_REG_POWERPC_R27,
	PERF_REG_POWERPC_R28,
	PERF_REG_POWERPC_R29,
	PERF_REG_POWERPC_R30,
	PERF_REG_POWERPC_R31,
	PERF_REG_POWERPC_NIP,
	PERF_REG_POWERPC_MSR,
	PERF_REG_POWERPC_ORIG_R3,
	PERF_REG_POWERPC_CTR,
	PERF_REG_POWERPC_LINK,
	PERF_REG_POWERPC_XER,
	PERF_REG_POWERPC_CCR,
	PERF_REG_POWERPC_SOFTE,
	PERF_REG_POWERPC_TRAP,
	PERF_REG_POWERPC_DAR,
	PERF_REG_POWERPC_DSISR,
	PERF_REG_POWERPC_ARCH_REGS,
	PERF_REG_POWERPC_MAX,
};

enum perf_event_powerpc_arch_regs {
	PERF_ARCH_REG_POWERPC_PVR,
	PERF_ARCH_REG_POWERPC_PMC1,
	PERF_ARCH_REG_POWERPC_PMC2,
	PERF_ARCH_REG_POWERPC_PMC3,
	PERF_ARCH_REG_POWERPC_PMC4,
	PERF_ARCH_REG_POWERPC_PMC5,
	PERF_ARCH_REG_POWERPC_PMC6,
	PERF_ARCH_REG_POWERPC_PMC7,
	PERF_ARCH_REG_POWERPC_PMC8,
	PERF_ARCH_REG_POWERPC_MMCR0,
	PERF_ARCH_REG_POWERPC_MMCR1,
	PERF_ARCH_REG_POWERPC_SIER,
	PERF_ARCH_REG_POWERPC_SIAR,
	PERF_ARCH_REG_POWERPC_SDAR,
	PERF_ARCH_REG_POWERPC_MMCRA,
	PERF_ARCH_REG_POWERPC_MMCR2,
	PERF_ARCH_REG_POWERPC_MAX,
};

#define PERF_ARCH_REG_PVR	1ULL<<PERF_ARCH_REG_POWERPC_PVR
#define PERF_ARCH_REG_PMC1	1ULL<<PERF_ARCH_REG_POWERPC_PMC1
#define PERF_ARCH_REG_PMC2	1ULL<<PERF_ARCH_REG_POWERPC_PMC2
#define PERF_ARCH_REG_PMC3	1ULL<<PERF_ARCH_REG_POWERPC_PMC3
#define PERF_ARCH_REG_PMC4	1ULL<<PERF_ARCH_REG_POWERPC_PMC4
#define PERF_ARCH_REG_PMC5	1ULL<<PERF_ARCH_REG_POWERPC_PMC5
#define PERF_ARCH_REG_PMC6	1ULL<<PERF_ARCH_REG_POWERPC_PMC6
#define PERF_ARCH_REG_PMC7	1ULL<<PERF_ARCH_REG_POWERPC_PMC7
#define PERF_ARCH_REG_PMC8	1ULL<<PERF_ARCH_REG_POWERPC_PMC8
#define PERF_ARCH_REG_MMCR0	1ULL<<PERF_ARCH_REG_POWERPC_MMCR0
#define PERF_ARCH_REG_MMCR1	1ULL<<PERF_ARCH_REG_POWERPC_MMCR1
#define PERF_ARCH_REG_SIER	1ULL<<PERF_ARCH_REG_POWERPC_SIER
#define PERF_ARCH_REG_SIAR	1ULL<<PERF_ARCH_REG_POWERPC_SIAR
#define PERF_ARCH_REG_SDAR	1ULL<<PERF_ARCH_REG_POWERPC_SDAR
#define PERF_ARCH_REG_MMCRA	1ULL<<PERF_ARCH_REG_POWERPC_MMCRA
#define PERF_ARCH_REG_MMCR2	1ULL<<PERF_ARCH_REG_POWERPC_MMCR2


#endif /* _UAPI_ASM_POWERPC_PERF_REGS_H */
