obj-$(CONFIG_TYPEC)		+= typec.o
typec-y				:= class.o
typec-y				+= altmode.o
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm.o
obj-y				+= fusb302/
obj-$(CONFIG_TYPEC_WCOVE)	+= typec_wcove.o
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi/
obj-y				+= altmodes/
