#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
#
# Generate system call table for perf. Derived from
# powerpc script.
#
# Copyright IBM Corp. 2017
# Author(s):  Hendrik Brueckner <brueckner@linux.vnet.ibm.com>
# Changed by: Ravi Bangoria <ravi.bangoria@linux.vnet.ibm.com>
# Changed by: Kim Phillips <kim.phillips@arm.com>

gcc=$1
hostcc=$2
input=$3

if ! test -r $input; then
	echo "Could not read input file" >&2
	exit 1
fi

create_table_from_c()
{
	local last_sc

	create_table_base=`mktemp -u /tmp/create-table-XXX`
	echo "#include <stdio.h>" > ${create_table_base}.c
	echo "#include \"$input\"" >> ${create_table_base}.c

	echo "int main(int argc, char *argv[])" >> ${create_table_base}.c
	echo "{" >> ${create_table_base}.c
	while read sc nr; do
		echo "	printf(\"\\\t[%d] = \\\"$sc\\\",\\\n\", __NR_$sc);" >> ${create_table_base}.c
		last_sc=$sc
	done
	echo "	printf(\"#define SYSCALLTBL_ARM64_MAX_ID %d\\\n\", __NR_$last_sc);" >> ${create_table_base}.c
	echo "}" >> ${create_table_base}.c

	$hostcc -o ${create_table_base}.x ${create_table_base}.c
	${create_table_base}.x
}

create_table()
{
	echo "static const char *syscalltbl_arm64[] = {"
	create_table_from_c
	echo '};'

	$RM -f ${create_table_base}.[cx]
}

$gcc -E -dM -x c  $input	       \
	|sed -ne 's/^#define __NR_//p' \
	|sort -t' ' -k2 -nu	       \
	|create_table
