obj-$(CONFIG_ARCH_THUNDER) += uncore_cavium.o		\
			      uncore_cavium_l2c_tad.o	\
			      uncore_cavium_l2c_cbc.o	\
			      uncore_cavium_lmc.o	\
			      uncore_cavium_ocx_lne.o	\
			      uncore_cavium_ocx_frc.o	\
			      uncore_cavium_ocx_tlk.o
