# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

generic-y += bitsperlong.h
generic-y += errno.h
generic-y += ioctl.h
generic-y += ipcbuf.h
generic-y += msgbuf.h
generic-y += param.h
generic-y += poll.h
generic-y += resource.h
generic-y += sembuf.h
generic-y += shmbuf.h
generic-y += siginfo.h
generic-y += socket.h
generic-y += sockios.h
generic-y += termbits.h
generic-y += termios.h

genhdr-y += unistd-common.h
genhdr-y += unistd-oabi.h
genhdr-y += unistd-eabi.h
