/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _ASM_X86_KVM_TYPES_H
#define _ASM_X86_KVM_TYPES_H

#define KVM_ARCH_WANT_MMU_MEMORY_CACHE

#define KVM_NR_MEM_OBJS 40

#define KVM_MMU_CACHE_GFP	GFP_KERNEL
#define KVM_MMU_CACHE_PAGE_GFP	GFP_KERNEL_ACCOUNT

#endif /* _ASM_X86_KVM_TYPES_H */
