#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# platform driver
obj-$(CONFIG_SND_SOC_MT2701) += mt2701-afe-pcm.o
obj-$(CONFIG_SND_SOC_MT2701) += mt2701-irq.o
obj-$(CONFIG_SND_SOC_MT2701) += mt2701-afe-clock-ctrl.o

# machine driver
obj-$(CONFIG_SND_SOC_MT2701_CS42448) += mt2701-cs42448.o
