/*
 * Synopsys Designware HDMI Receiver controller driver
 *
 * This Synopsys dw-hdmi-rx software and associated documentation
 * (hereinafter the "Software") is an unsupported proprietary work of
 * Synopsys, Inc. unless otherwise expressly agreed to in writing between
 * Synopsys and you. The Software IS NOT an item of Licensed Software or a
 * Licensed Product under any End User Software License Agreement or
 * Agreement for Licensed Products with Synopsys or any supplement thereto.
 * Synopsys is a registered trademark of Synopsys, Inc. Other names included
 * in the SOFTWARE may be the trademarks of their respective owners.
 *
 * The contents of this file are dual-licensed; you may select either version 2
 * of the GNU General Public License (“GPL”) or the MIT license (“MIT”).
 *
 * Copyright (c) 2017 Synopsys, Inc. and/or its affiliates.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS"  WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING, BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT, OR OTHERWISE
 * ARISING FROM, OUT OF, OR IN CONNECTION WITH THE SOFTWARE THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 */

#ifndef __DW_HDMI_RX_H__
#define __DW_HDMI_RX_H__

#include <linux/bitops.h>

/* id_hdmi Registers */
#define HDMI_SETUP_CTRL				0x0000
#define HDMI_PLL_LCK_STS			0x0030
#define HDMI_CKM_EVLTM				0x0094
#define HDMI_CKM_RESULT				0x009c
#define HDMI_STS				0x00bc

/* id_hdcp_1_4 Registers */
#define HDMI_HDCP_CTRL				0x00c0
#define HDMI_HDCP_SETTINGS			0x00c4
#define HDMI_HDCP_SEED				0x00c8
#define HDMI_HDCP_BKSV1				0x00cc
#define HDMI_HDCP_BKSV0				0x00d0
#define HDMI_HDCP_KIDX				0x00d4
#define HDMI_HDCP_KEY1				0x00d8
#define HDMI_HDCP_KEY0				0x00dc
#define HDMI_HDCP_DBG				0x00e0
#define HDMI_HDCP_AKSV1				0x00e4
#define HDMI_HDCP_AKSV0				0x00e8
#define HDMI_HDCP_AN1				0x00ec
#define HDMI_HDCP_AN0				0x00f0
#define HDMI_HDCP_EESS_WOO			0x00f4
#define HDMI_HDCP_I2C_TIMEOUT			0x00f8
#define HDMI_HDCP_STS				0x00fc

/* id_mode_detection Registers */
#define HDMI_MD_HT0				0x0148
#define HDMI_MD_HT1				0x014c
#define HDMI_MD_HACT_PX				0x0150
#define HDMI_MD_VCTRL				0x0158
#define HDMI_MD_VOL				0x0164
#define HDMI_MD_VAL				0x0168
#define HDMI_MD_VTL				0x0170
#define HDMI_MD_STS				0x0180

/* id_phy_configuration Registers */
#define HDMI_PHY_CTRL				0x02c0
#define HDMI_PHY_JTAG_CONF			0x02ec
#define HDMI_PHY_JTAG_TAP_TCLK			0x02f0
#define HDMI_PHY_JTAG_TAP_IN			0x02f4
#define HDMI_PHY_JTAG_TAP_OUT			0x02f8
#define HDMI_PHY_JTAG_ADDR			0x02fc

/* id_packet_decoder Registers */
#define HDMI_PDEC_STS				0x0360
#define HDMI_PDEC_VSI_PAYLOAD0			0x0368
#define HDMI_PDEC_AVI_PB			0x03a4

/* id_hdmi_2_0 Registers */
#define HDMI_SCDC_CONFIG			0x0808
#define HDMI_HDCP22_CONTROL			0x081c
#define HDMI_HDCP22_STATUS			0x08fc

/* id_audio_and_cec_interrupt Registers */
#define HDMI_AUD_CEC_IEN_CLR			0x0f90
#define HDMI_AUD_CEC_IEN_SET			0x0f94
#define HDMI_AUD_CEC_ISTS			0x0f98
#define HDMI_AUD_CEC_IEN			0x0f9c
#define HDMI_AUD_CEC_ICLR			0x0fa0
#define HDMI_AUD_CEC_ISET			0x0fa4

/* id_mode_detection_interrupt Registers */
#define HDMI_MD_IEN_CLR				0x0fc0
#define HDMI_MD_IEN_SET				0x0fc4
#define HDMI_MD_ISTS				0x0fc8
#define HDMI_MD_IEN				0x0fcc
#define HDMI_MD_ICLR				0x0fd0
#define HDMI_MD_ISET				0x0fd4

/* id_hdmi_interrupt Registers */
#define HDMI_IEN_CLR				0x0fd8
#define HDMI_IEN_SET				0x0fdc
#define HDMI_ISTS				0x0fe0
#define HDMI_IEN				0x0fe4
#define HDMI_ICLR				0x0fe8
#define HDMI_ISET				0x0fec

/* id_dmi Registers */
#define HDMI_DMI_SW_RST				0x0ff0

/* id_cec Registers */
#define HDMI_CEC_CTRL				0x1f00
#define HDMI_CEC_MASK				0x1f08
#define HDMI_CEC_ADDR_L				0x1f14
#define HDMI_CEC_ADDR_H				0x1f18
#define HDMI_CEC_TX_CNT				0x1f1c
#define HDMI_CEC_RX_CNT				0x1f20
#define HDMI_CEC_TX_DATA(i)			(0x1f40 + ((i) * 4))
#define HDMI_CEC_TX_DATA_MAX			16
#define HDMI_CEC_RX_DATA(i)			(0x1f80 + ((i) * 4))
#define HDMI_CEC_RX_DATA_MAX			16
#define HDMI_CEC_LOCK				0x1fc0
#define HDMI_CEC_WAKEUPCTRL			0x1fc4

/* id_cbus Registers */
#define HDMI_CBUSIOCTRL				0x3020

enum {
	/* SETUP_CTRL field values */
	HDMI_SETUP_CTRL_HOT_PLUG_DETECT_INPUT_X_MASK = GENMASK(27,24),
	HDMI_SETUP_CTRL_HOT_PLUG_DETECT_INPUT_X_OFFSET = 24,
	HDMI_SETUP_CTRL_HDMIBUS_RESET_OVR_EN_MASK = BIT(21),
	HDMI_SETUP_CTRL_HDMIBUS_RESET_OVR_EN_OFFSET = 21,
	HDMI_SETUP_CTRL_BUS_RESET_OVR_MASK = BIT(20),
	HDMI_SETUP_CTRL_BUS_RESET_OVR_OFFSET = 20,
	HDMI_SETUP_CTRL_HDMI_RESET_OVR_MASK = BIT(19),
	HDMI_SETUP_CTRL_HDMI_RESET_OVR_OFFSET = 19,
	HDMI_SETUP_CTRL_PON_RESET_OVR_MASK = BIT(18),
	HDMI_SETUP_CTRL_PON_RESET_OVR_OFFSET = 18,
	HDMI_SETUP_CTRL_RESET_OVR_MASK = BIT(17),
	HDMI_SETUP_CTRL_RESET_OVR_OFFSET = 17,
	HDMI_SETUP_CTRL_RESET_OVR_EN_MASK = BIT(16),
	HDMI_SETUP_CTRL_RESET_OVR_EN_OFFSET = 16,
	HDMI_SETUP_CTRL_EQ_OSM_OVR_MASK = BIT(15),
	HDMI_SETUP_CTRL_EQ_OSM_OVR_OFFSET = 15,
	HDMI_SETUP_CTRL_EQ_OSM_OVR_EN_MASK = BIT(14),
	HDMI_SETUP_CTRL_EQ_OSM_OVR_EN_OFFSET = 14,
	HDMI_SETUP_CTRL_NOWAIT_ACTIVITY_MASK = BIT(13),
	HDMI_SETUP_CTRL_NOWAIT_ACTIVITY_OFFSET = 13,
	HDMI_SETUP_CTRL_EQ_CAL_TIME_MASK = GENMASK(12,7),
	HDMI_SETUP_CTRL_EQ_CAL_TIME_OFFSET = 7,
	HDMI_SETUP_CTRL_USE_PLL_LOCK_MASK = BIT(6),
	HDMI_SETUP_CTRL_USE_PLL_LOCK_OFFSET = 6,
	HDMI_SETUP_CTRL_FORCE_STATE_MASK = BIT(5),
	HDMI_SETUP_CTRL_FORCE_STATE_OFFSET = 5,
	HDMI_SETUP_CTRL_TARGET_STATE_MASK = GENMASK(4,1),
	HDMI_SETUP_CTRL_TARGET_STATE_OFFSET = 1,
	HDMI_SETUP_CTRL_HOT_PLUG_DETECT_MASK = BIT(0),
	HDMI_SETUP_CTRL_HOT_PLUG_DETECT_OFFSET = 0,
	/* PLL_LCK_STS field values */
	HDMI_PLL_LCK_STS_PLL_LOCKED = BIT(0),
	/* CKM_EVLTM field values */
	HDMI_CKM_EVLTM_LOCK_HYST_MASK = GENMASK(21,20),
	HDMI_CKM_EVLTM_LOCK_HYST_OFFSET = 20,
	HDMI_CKM_EVLTM_CLK_HYST_MASK = GENMASK(18,16),
	HDMI_CKM_EVLTM_CLK_HYST_OFFSET = 16,
	HDMI_CKM_EVLTM_EVAL_TIME_MASK = GENMASK(15,4),
	HDMI_CKM_EVLTM_EVAL_TIME_OFFSET = 4,
	HDMI_CKM_EVLTM_CLK_MEAS_INPUT_SRC_MASK = BIT(0),
	HDMI_CKM_EVLTM_CLK_MEAS_INPUT_SRC_OFFSET = 0,
	/* CKM_RESULT field values */
	HDMI_CKM_RESULT_CLOCK_IN_RANGE = BIT(17),
	HDMI_CKM_RESULT_FREQ_LOCKED = BIT(16),
	HDMI_CKM_RESULT_CLKRATE_MASK = GENMASK(15,0),
	HDMI_CKM_RESULT_CLKRATE_OFFSET = 0,
	/* STS field values */
	HDMI_STS_DCM_CURRENT_MODE_MASK = GENMASK(31,28),
	HDMI_STS_DCM_CURRENT_MODE_OFFSET = 28,
	HDMI_STS_DCM_LAST_PIXEL_PHASE_STS_MASK = GENMASK(27,24),
	HDMI_STS_DCM_LAST_PIXEL_PHASE_STS_OFFSET = 24,
	HDMI_STS_DCM_PHASE_DIFF_CNT_MASK = GENMASK(23,16),
	HDMI_STS_DCM_PH_DIFF_CNT_OVERFL = BIT(15),
	HDMI_STS_DCM_GCP_ZERO_FIELDS_PASS = BIT(14),
	HDMI_STS_CTL3_STS = BIT(13),
	HDMI_STS_CTL2_STS = BIT(12),
	HDMI_STS_CTL1_STS = BIT(11),
	HDMI_STS_CTL0_STS = BIT(10),
	HDMI_STS_VS_POL_ADJ_STS = BIT(9),
	HDMI_STS_HS_POL_ADJ_STS = BIT(8),
	HDMI_STS_RES_OVERLOAD_STS = BIT(7),
	HDMI_STS_DCM_CURRENT_PP_MASK = GENMASK(3,0),
	HDMI_STS_DCM_CURRENT_PP_OFFSET = 0,
	/* HDCP_CTRL field values */
	HDMI_HDCP_CTRL_ENDISLOCK_MASK = BIT(25),
	HDMI_HDCP_CTRL_ENDISLOCK_OFFSET = 25,
	HDMI_HDCP_CTRL_ENABLE_MASK = BIT(24),
	HDMI_HDCP_CTRL_ENABLE_OFFSET = 24,
	HDMI_HDCP_CTRL_FREEZE_HDCP_FSM_MASK = BIT(21),
	HDMI_HDCP_CTRL_FREEZE_HDCP_FSM_OFFSET = 21,
	HDMI_HDCP_CTRL_FREEZE_HDCP_STATE_MASK = GENMASK(20,15),
	HDMI_HDCP_CTRL_FREEZE_HDCP_STATE_OFFSET = 15,
	HDMI_HDCP_CTRL_VID_DE_MASK = BIT(14),
	HDMI_HDCP_CTRL_VID_DE_OFFSET = 14,
	HDMI_HDCP_CTRL_SEL_AVMUTE_MASK = GENMASK(11,10),
	HDMI_HDCP_CTRL_SEL_AVMUTE_OFFSET = 10,
	HDMI_HDCP_CTRL_CTL_MASK = GENMASK(9,8),
	HDMI_HDCP_CTRL_CTL_OFFSET = 8,
	HDMI_HDCP_CTRL_RI_RATE_MASK = GENMASK(7,6),
	HDMI_HDCP_CTRL_RI_RATE_OFFSET = 6,
	HDMI_HDCP_CTRL_HDMI_MODE_ENABLE_MASK = BIT(2),
	HDMI_HDCP_CTRL_HDMI_MODE_ENABLE_OFFSET = 2,
	HDMI_HDCP_CTRL_KEY_DECRYPT_ENABLE_MASK = BIT(1),
	HDMI_HDCP_CTRL_KEY_DECRYPT_ENABLE_OFFSET = 1,
	HDMI_HDCP_CTRL_ENC_EN_MASK = BIT(0),
	HDMI_HDCP_CTRL_ENC_EN_OFFSET = 0,
	/* HDCP_SEED field values */
	HDMI_HDCP_SEED_KEY_DECRYPT_SEED_MASK = GENMASK(15,0),
	HDMI_HDCP_SEED_KEY_DECRYPT_SEED_OFFSET = 0,
	/* HDCP_STS field values */
	HDMI_HDCP_STS_ENC_STATE = BIT(9),
	HDMI_HDCP_STS_AUTH_START = BIT(8),
	HDMI_HDCP_STS_KEY_WR_OK = BIT(0),
	/* MD_HT0 field values */
	HDMI_MD_HT0_HTOT32_CLK_MASK = GENMASK(31,16),
	HDMI_MD_HT0_HTOT32_CLK_OFFSET = 16,
	HDMI_MD_HT0_HS_CLK_MASK = GENMASK(15,0),
	HDMI_MD_HT0_HS_CLK_OFFSET = 0,
	/* MD_HT1 field values */
	HDMI_MD_HT1_HTOT_PIX_MASK = GENMASK(31,16),
	HDMI_MD_HT1_HTOT_PIX_OFFSET = 16,
	HDMI_MD_HT1_HOFS_PIX_MASK = GENMASK(15,0),
	HDMI_MD_HT1_HOFS_PIX_OFFSET = 0,
	/* MD_VCTRL field values */
	HDMI_MD_VCTRL_V_OFFS_LIN_MODE_MASK = BIT(4),
	HDMI_MD_VCTRL_V_OFFS_LIN_MODE_OFFSET = 4,
	HDMI_MD_VCTRL_V_EDGE_MASK = BIT(1),
	HDMI_MD_VCTRL_V_EDGE_OFFSET = 1,
	HDMI_MD_VCTRL_V_MODE_MASK = BIT(0),
	HDMI_MD_VCTRL_V_MODE_OFFSET = 0,
	/* MD_STS field values */
	HDMI_MD_STS_ILACE = BIT(3),
	HDMI_MD_STS_DE_ACTIVITY = BIT(2),
	HDMI_MD_STS_VS_ACT = BIT(1),
	HDMI_MD_STS_HS_ACT = BIT(0),
	/* PHY_CTRL field values */
	HDMI_PHY_CTRL_SVSRETMODEZ_MASK = BIT(6),
	HDMI_PHY_CTRL_SVSRETMODEZ_OFFSET = 6,
	HDMI_PHY_CTRL_CFGCLKFREQ_MASK = GENMASK(5,4),
	HDMI_PHY_CTRL_CFGCLKFREQ_OFFSET = 4,
	HDMI_PHY_CTRL_PORTSELECT_MASK = GENMASK(3,2),
	HDMI_PHY_CTRL_PORTSELECT_OFFSET = 2,
	HDMI_PHY_CTRL_PDDQ_MASK = BIT(1),
	HDMI_PHY_CTRL_PDDQ_OFFSET = 1,
	HDMI_PHY_CTRL_RESET_MASK = BIT(0),
	HDMI_PHY_CTRL_RESET_OFFSET = 0,
	/* PHY_JTAG_TAP_IN field values */
	HDMI_PHY_JTAG_TAP_IN_TMS = BIT(4),
	HDMI_PHY_JTAG_TAP_IN_TDI = BIT(0),
	/* PDEC_STS field values */
	HDMI_PDEC_STS_DRM_CKS_CHG = BIT(31),
	HDMI_PDEC_STS_DRM_RCV = BIT(30),
	HDMI_PDEC_STS_NTSCVBI_CKS_CHG = BIT(29),
	HDMI_PDEC_STS_DVIDET = BIT(28),
	HDMI_PDEC_STS_VSI_CKS_CHG = BIT(27),
	HDMI_PDEC_STS_GMD_CKS_CHG = BIT(26),
	HDMI_PDEC_STS_AIF_CKS_CHG = BIT(25),
	HDMI_PDEC_STS_AVI_CKS_CHG = BIT(24),
	HDMI_PDEC_STS_ACR_N_CHG = BIT(23),
	HDMI_PDEC_STS_ACR_CTS_CHG = BIT(22),
	HDMI_PDEC_STS_GCP_AV_MUTE_CHG = BIT(21),
	HDMI_PDEC_STS_GMD_RCV = BIT(20),
	HDMI_PDEC_STS_AIF_RCV = BIT(19),
	HDMI_PDEC_STS_AVI_RCV = BIT(18),
	HDMI_PDEC_STS_ACR_RCV = BIT(17),
	HDMI_PDEC_STS_GCP_RCV = BIT(16),
	HDMI_PDEC_STS_VSI_RCV = BIT(15),
	HDMI_PDEC_STS_AMP_RCV = BIT(14),
	HDMI_PDEC_STS_NTSCVBI_RCV = BIT(13),
	HDMI_PDEC_STS_OBA_LAYOUT = BIT(12),
	HDMI_PDEC_STS_AUDS_LAYOUT = BIT(11),
	HDMI_PDEC_STS_PD_FIFO_NEW_ENTRY = BIT(8),
	HDMI_PDEC_STS_PD_FIFO_OVERFL = BIT(4),
	HDMI_PDEC_STS_PD_FIFO_UNDERFL = BIT(3),
	HDMI_PDEC_STS_PD_FIFO_TH_START_PASS = BIT(2),
	HDMI_PDEC_STS_PD_FIFO_TH_MAX_PASS = BIT(1),
	HDMI_PDEC_STS_PD_FIFO_TH_MIN_PASS = BIT(0),
	/* PDEC_VSI_PAYLOAD0 field values */
	HDMI_PDEC_VSI_PAYLOAD0_HDMI_VIC_MASK = GENMASK(15,8),
	HDMI_PDEC_VSI_PAYLOAD0_HDMI_VIC_OFFSET = 8,
	/* PDEC_AVI_PB field values */
	HDMI_PDEC_AVI_PB_VID_IDENT_CODE_MASK = GENMASK(31,24),
	HDMI_PDEC_AVI_PB_VID_IDENT_CODE_OFFSET = 24,
	HDMI_PDEC_AVI_PB_IT_CONTENT = BIT(23),
	HDMI_PDEC_AVI_PB_EXT_COLORIMETRY_MASK = GENMASK(22,20),
	HDMI_PDEC_AVI_PB_EXT_COLORIMETRY_OFFSET = 20,
	HDMI_PDEC_AVI_PB_RGB_QUANT_RANGE_MASK = GENMASK(19,18),
	HDMI_PDEC_AVI_PB_RGB_QUANT_RANGE_OFFSET = 18,
	HDMI_PDEC_AVI_PB_NON_UNIF_SCALE_MASK = GENMASK(17,16),
	HDMI_PDEC_AVI_PB_NON_UNIF_SCALE_OFFSET = 16,
	HDMI_PDEC_AVI_PB_COLORIMETRY_MASK = GENMASK(15,14),
	HDMI_PDEC_AVI_PB_COLORIMETRY_OFFSET = 14,
	HDMI_PDEC_AVI_PB_PIC_ASPECT_RAT_MASK = GENMASK(13,12),
	HDMI_PDEC_AVI_PB_PIC_ASPECT_RAT_OFFSET = 12,
	HDMI_PDEC_AVI_PB_ACT_ASPECT_RAT_MASK = GENMASK(11,8),
	HDMI_PDEC_AVI_PB_ACT_ASPECT_RAT_OFFSET = 8,
	HDMI_PDEC_AVI_PB_VIDEO_FORMAT_MASK = GENMASK(7,5),
	HDMI_PDEC_AVI_PB_VIDEO_FORMAT_OFFSET = 5,
	HDMI_PDEC_AVI_PB_ACT_INFO_PRESENT = BIT(4),
	HDMI_PDEC_AVI_PB_BAR_INFO_VALID_MASK = GENMASK(3,2),
	HDMI_PDEC_AVI_PB_BAR_INFO_VALID_OFFSET = 2,
	HDMI_PDEC_AVI_PB_SCAN_INFO_MASK = GENMASK(1,0),
	HDMI_PDEC_AVI_PB_SCAN_INFO_OFFSET = 0,
	/* SCDC_CONFIG field values */
	HDMI_SCDC_CONFIG_HPDLOW_MASK = BIT(1),
	HDMI_SCDC_CONFIG_HPDLOW_OFFSET = 1,
	HDMI_SCDC_CONFIG_POWERPROVIDED_MASK = BIT(0),
	HDMI_SCDC_CONFIG_POWERPROVIDED_OFFSET = 0,
	/* HDCP22_CONTROL field values */
	HDMI_HDCP22_CONTROL_CD_OVR_VAL_MASK = GENMASK(23,20),
	HDMI_HDCP22_CONTROL_CD_OVR_VAL_OFFSET = 20,
	HDMI_HDCP22_CONTROL_CD_OVR_EN_MASK = BIT(16),
	HDMI_HDCP22_CONTROL_CD_OVR_EN_OFFSET = 16,
	HDMI_HDCP22_CONTROL_HPD_MASK = BIT(12),
	HDMI_HDCP22_CONTROL_HPD_OFFSET = 12,
	HDMI_HDCP22_CONTROL_PKT_ERR_OVR_VAL_MASK = BIT(9),
	HDMI_HDCP22_CONTROL_PKT_ERR_OVR_VAL_OFFSET= 9,
	HDMI_HDCP22_CONTROL_PKT_ERR_OVR_EN_MASK = BIT(8),
	HDMI_HDCP22_CONTROL_PKT_ERR_OVR_EN_OFFSET = 8,
	HDMI_HDCP22_CONTROL_AVMUTE_OVR_VAL_MASK = BIT(5),
	HDMI_HDCP22_CONTROL_AVMUTE_OVR_VAL_OFFSET = 5,
	HDMI_HDCP22_CONTROL_AVMUTE_OVR_EN_MASK = BIT(4),
	HDMI_HDCP22_CONTROL_AVMUTE_OVR_EN_OFFSET = 4,
	HDMI_HDCP22_CONTROL_OVR_VAL_MASK = BIT(2),
	HDMI_HDCP22_CONTROL_OVR_VAL_OFFSET = 2,
	HDMI_HDCP22_CONTROL_OVR_EN_MASK = BIT(1),
	HDMI_HDCP22_CONTROL_OVR_EN_OFFSET = 1,
	HDMI_HDCP22_CONTROL_SWITCH_LCK_MASK = BIT(0),
	HDMI_HDCP22_CONTROL_SWITCH_LCK_OFFSET = 0,
	/* AUD_CEC_ISTS field values */
	HDMI_AUD_CEC_ISTS_WAKEUPCTRL = BIT(22),
	HDMI_AUD_CEC_ISTS_ERROR_FOLL = BIT(21),
	HDMI_AUD_CEC_ISTS_ERROR_INIT = BIT(20),
	HDMI_AUD_CEC_ISTS_ARBLST = BIT(19),
	HDMI_AUD_CEC_ISTS_NACK = BIT(18),
	HDMI_AUD_CEC_ISTS_EOM = BIT(17),
	HDMI_AUD_CEC_ISTS_DONE = BIT(16),
	HDMI_AUD_CEC_ISTS_SCK_STABLE = BIT(1),
	HDMI_AUD_CEC_ISTS_CTSN_CNT = BIT(0),
	/* MD_ISTS field values */
	HDMI_MD_ISTS_VOFS_LIN = BIT(11),
	HDMI_MD_ISTS_VTOT_LIN = BIT(10),
	HDMI_MD_ISTS_VACT_LIN = BIT(9),
	HDMI_MD_ISTS_VS_CLK = BIT(8),
	HDMI_MD_ISTS_VTOT_CLK = BIT(7),
	HDMI_MD_ISTS_HACT_PIX = BIT(6),
	HDMI_MD_ISTS_HS_CLK = BIT(5),
	HDMI_MD_ISTS_HTOT32_CLK = BIT(4),
	HDMI_MD_ISTS_ILACE = BIT(3),
	HDMI_MD_ISTS_DE_ACTIVITY = BIT(2),
	HDMI_MD_ISTS_VS_ACT = BIT(1),
	HDMI_MD_ISTS_HS_ACT = BIT(0),
	/* ISTS field values */
	HDMI_ISTS_I2CMP_ARBLOST = BIT(30),
	HDMI_ISTS_I2CMPNACK = BIT(29),
	HDMI_ISTS_I2CMPDONE = BIT(28),
	HDMI_ISTS_VS_THR_REACHED = BIT(27),
	HDMI_ISTS_VSYNC_ACT_EDGE = BIT(26),
	HDMI_ISTS_AKSV_RCV = BIT(25),
	HDMI_ISTS_PLL_CLOCK_GATED = BIT(24),
	HDMI_ISTS_DESER_MISAL = BIT(23),
	HDMI_ISTS_CDSENSE_CHG = BIT(22),
	HDMI_ISTS_CEAVID_EMPTY = BIT(21),
	HDMI_ISTS_CEAVID_FULL = BIT(20),
	HDMI_ISTS_SCDCTMDSCFGCHANGE = BIT(19),
	HDMI_ISTS_SCDCSCSTATUSCHANGE = BIT(18),
	HDMI_ISTS_SCDCCFGCHANGE = BIT(17),
	HDMI_ISTS_DCM_CURRENT_MODE_CHG = BIT(16),
	HDMI_ISTS_DCM_PH_DIFF_CNT_OVERFL = BIT(15),
	HDMI_ISTS_DCM_GCP_ZERO_FIELDS_PASS = BIT(14),
	HDMI_ISTS_CTL3_CHANGE = BIT(13),
	HDMI_ISTS_CTL2_CHANGE = BIT(12),
	HDMI_ISTS_CTL1_CHANGE = BIT(11),
	HDMI_ISTS_CTL0_CHANGE = BIT(10),
	HDMI_ISTS_VS_POL_ADJ = BIT(9),
	HDMI_ISTS_HS_POL_ADJ = BIT(8),
	HDMI_ISTS_RES_OVERLOAD = BIT(7),
	HDMI_ISTS_CLK_CHANGE = BIT(6),
	HDMI_ISTS_PLL_LCK_CHG = BIT(5),
	HDMI_ISTS_EQGAIN_DONE = BIT(4),
	HDMI_ISTS_OFFSCAL_DONE = BIT(3),
	HDMI_ISTS_RESCAL_DONE = BIT(2),
	HDMI_ISTS_ACT_CHANGE = BIT(1),
	HDMI_ISTS_STATE_REACHED = BIT(0),
	/* DMI_SW_RST field values */
	HDMI_DMI_SW_RST_TMDS = BIT(16),
	HDMI_DMI_SW_RST_HDCP = BIT(8),
	HDMI_DMI_SW_RST_VID = BIT(7),
	HDMI_DMI_SW_RST_PIXEL = BIT(6),
	HDMI_DMI_SW_RST_CEC = BIT(5),
	HDMI_DMI_SW_RST_AUD = BIT(4),
	HDMI_DMI_SW_RST_BUS = BIT(3),
	HDMI_DMI_SW_RST_HDMI = BIT(2),
	HDMI_DMI_SW_RST_MODET = BIT(1),
	HDMI_DMI_SW_RST_MAIN = BIT(0),
	/* CEC_CTRL field values */
	HDMI_CEC_CTRL_STANDBY_MASK = BIT(4),
	HDMI_CEC_CTRL_STANDBY_OFFSET = 4,
	HDMI_CEC_CTRL_BC_NACK_MASK = BIT(3),
	HDMI_CEC_CTRL_BC_NACK_OFFSET = 3,
	HDMI_CEC_CTRL_FRAME_TYP_MASK = GENMASK(2,1),
	HDMI_CEC_CTRL_FRAME_TYP_OFFSET = 1,
	HDMI_CEC_CTRL_SEND_MASK = BIT(0),
	HDMI_CEC_CTRL_SEND_OFFSET = 0,
	/* CEC_MASK field values */
	HDMI_CEC_MASK_WAKEUP_MASK = BIT(6),
	HDMI_CEC_MASK_WAKEUP_OFFSET = 6,
	HDMI_CEC_MASK_ERROR_FLOW_MASK = BIT(5),
	HDMI_CEC_MASK_ERROR_FLOW_OFFSET = 5,
	HDMI_CEC_MASK_ERROR_INITITATOR_MASK = BIT(4),
	HDMI_CEC_MASK_ERROR_INITITATOR_OFFSET = 4,
	HDMI_CEC_MASK_ARB_LOST_MASK = BIT(3),
	HDMI_CEC_MASK_ARB_LOST_OFFSET = 3,
	HDMI_CEC_MASK_NACK_MASK = BIT(2),
	HDMI_CEC_MASK_NACK_OFFSET = 2,
	HDMI_CEC_MASK_EOM_MASK = BIT(1),
	HDMI_CEC_MASK_EOM_OFFSET = 1,
	HDMI_CEC_MASK_DONE_MASK = BIT(0),
	HDMI_CEC_MASK_DONE_OFFSET = 0,
	/* CBUSIOCTRL field values */
	HDMI_CBUSIOCTRL_DATAPATH_CBUSZ_MASK = BIT(24),
	HDMI_CBUSIOCTRL_DATAPATH_CBUSZ_OFFSET = 24,
	HDMI_CBUSIOCTRL_SVSRETMODEZ_MASK = BIT(16),
	HDMI_CBUSIOCTRL_SVSRETMODEZ_OFFSET = 16,
	HDMI_CBUSIOCTRL_PDDQ_MASK = BIT(8),
	HDMI_CBUSIOCTRL_PDDQ_OFFSET = 8,
	HDMI_CBUSIOCTRL_RESET_MASK = BIT(0),
	HDMI_CBUSIOCTRL_RESET_OFFSET = 0,
};

#endif /* __DW_HDMI_RX_H__ */
