obj-$(CONFIG_DWC_MIPI_CSI2_HOST_PLATFORM)	+= dw-csi-platfrm.o
dw-csi-platfrm-objs		:= dw-csi-plat.o dw-mipi-csi.o
obj-$(CONFIG_DWC_MIPI_TC_DPHY_G128)	+= dw-dphy-platfrm.o
dw-dphy-platfrm-objs	:= dw-dphy-plat.o dw-dphy-rx.o
