#ifndef _UAPI__LINUX_CHECMATE_H__
#define _UAPI__LINUX_CHECMATE_H__

#define CHECMATE_INSTALL_HOOK 1
#define CHECMATE_DENY_RESET 2
#define CHECMATE_RESET 3

enum checmate_hook {
	CHECMATE_HOOK_UNSPEC,
	/* CONFIG_SECURITY_NET hooks */
	CHECMATE_HOOK_UNIX_STREAM_CONNECT,
	CHECMATE_HOOK_UNIX_MAY_SEND,
	CHECMATE_HOOK_SOCKET_CREATE,
	CHECMATE_HOOK_SOCKET_POST_CREATE,
	CHECMATE_HOOK_SOCKET_BIND,
	CHECMATE_HOOK_SOCKET_CONNECT,
	CHECMATE_HOOK_SOCKET_LISTEN,
	CHECMATE_HOOK_SOCKET_ACCEPT,
	CHECMATE_HOOK_SOCKET_SENDMSG,
	CHECMATE_HOOK_SOCKET_RECVMSG,
	CHECMATE_HOOK_SOCKET_GETSOCKNAME,
	CHECMATE_HOOK_SOCKET_GETPEERNAME,
	CHECMATE_HOOK_SOCKET_GETSOCKOPT,
	CHECMATE_HOOK_SOCKET_SETSOCKOPT,
	CHECMATE_HOOK_SOCKET_SHUTDOWN,
	CHECMATE_HOOK_SOCKET_SOCK_RCV_SKB,
	CHECMATE_HOOK_SOCKET_GETPEERSEC_STREAM,
	CHECMATE_HOOK_SOCKET_GETPEERSEC_DGRAM,
	CHECMATE_HOOK_SK_ALLOC_SECURITY,
	CHECMATE_HOOK_SK_FREE_SECURITY,
	CHECMATE_HOOK_SK_CLONE_SECURITY,
	CHECMATE_HOOK_SK_GETSECID,
	CHECMATE_HOOK_SOCK_GRAFT,
	CHECMATE_HOOK_INET_CONN_REQUEST,
	CHECMATE_HOOK_INET_CSK_CLONE,
	CHECMATE_HOOK_INET_CONN_ESTABLISHED,
	CHECMATE_HOOK_SECMARK_RELABEL_PACKET,
	CHECMATE_HOOK_SECMARK_REFCOUNT_INC,
	CHECMATE_HOOK_SECMARK_REFCOUNT_DEC,
	CHECMATE_HOOK_REQ_CLASSIFY_FLOW,
	CHECMATE_HOOK_TUN_DEV_ALLOC_SECURITY,
	CHECMATE_HOOK_TUN_DEV_FREE_SECURITY,
	CHECMATE_HOOK_TUN_DEV_CREATE,
	CHECMATE_HOOK_TUN_DEV_ATTACH_QUEUE,
	CHECMATE_HOOK_TUN_DEV_ATTACH,
	CHECMATE_HOOK_TUN_DEV_OPEN,
	/* CONFIG_SECURITY_PATH hooks */
	CHECMATE_HOOK_PATH_UNLINK,
	CHECMATE_HOOK_PATH_MKDIR,
	CHECMATE_HOOK_PATH_RMDIR,
	CHECMATE_HOOK_PATH_MKNOD,
	CHECMATE_HOOK_PATH_TRUNCATE,
	CHECMATE_HOOK_PATH_SYMLINK,
	CHECMATE_HOOK_PATH_LINK,
	CHECMATE_HOOK_PATH_RENAME,
	CHECMATE_HOOK_PATH_CHMOD,
	CHECMATE_HOOK_PATH_CHOWN,
	CHECMATE_HOOK_PATH_CHROOT,
	/* Other hooks */
	CHECMATE_HOOK_FILE_OPEN,
	CHECMATE_HOOK_TASK_CREATE,
	CHECMATE_HOOK_TASK_FREE,
	__CHECMATE_HOOK_MAX,
};
#endif
