# UAPI Header export list

ifeq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/uapi/asm/a.out.h \
		 $(srctree)/arch/$(SRCARCH)/include/asm/a.out.h),)
header-n += a.out.h
endif

ifeq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/uapi/asm/kvm.h \
		 $(srctree)/arch/$(SRCARCH)/include/asm/kvm.h),)
header-n += kvm.h
endif

ifeq ($(wildcard $(srctree)/arch/$(SRCARCH)/include/uapi/asm/kvm_para.h \
		 $(srctree)/arch/$(SRCARCH)/include/asm/kvm_para.h),)
header-n += kvm_para.h
endif
