bus1-y :=			\
	handle.o		\
	main.o			\
	peer.o			\
	tx.o			\
	user.o			\
	util.o			\
	util/active.o		\
	util/flist.o		\
	util/pool.o		\
	util/queue.o

obj-$(CONFIG_BUS1) += bus1.o

bus1-$(CONFIG_BUS1_TESTS) += tests.o
