#!/usr/bin/perl
#
# Build a mapping table for C definitions.
#
# Copyright (c) 2017 Hannes Reinecke, SUSE Linux GmbH.
# All rights reserved.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public Licence
# as published by the Free Software Foundation; either version
# 2 of the Licence, or (at your option) any later version.
#

my $prf;

$prf = $ARGV[0];
open IN_FILE, "<$ARGV[1]" || die;
print "\t/*\n\t * Automatically generated by ", $0, ".\n";
print "\t * Do not edit.\n\t */\n";
while (<IN_FILE>) {
    chomp;
    if (/^#define ${prf}_([^[:blank:]]*).*/) {
	print "\t{ ", $prf, "_", $1, ", \"", $1, "\" },\n";
    }
}
close IN_FILE || die;
