# UFSHCD makefile
obj-$(CONFIG_SCSI_UFS_DWC) += ufshcd-dwc.o
obj-$(CONFIG_SCSI_UFS_DWC_TC) += tc-dwc-g210.o
obj-$(CONFIG_SCSI_UFS_QCOM) += ufs-qcom.o
obj-$(CONFIG_SCSI_UFSHCD) += ufshcd.o
obj-$(CONFIG_SCSI_UFSHCD_PCI) += ufshcd-pci.o
obj-$(CONFIG_SCSI_UFSHCD_PLATFORM) += ufshcd-pltfrm.o
