#
# Makefile for industrial I/O temperature drivers
#

obj-$(CONFIG_MCP9808) += mcp9808.o
obj-$(CONFIG_MLX90614) += mlx90614.o
obj-$(CONFIG_TMP006) += tmp006.o
obj-$(CONFIG_TSYS01) += tsys01.o
obj-$(CONFIG_TSYS02D) += tsys02d.o
