#include "clang-bpf-includes.h"
const char clang_builtin_bpf_funcs_str[] =
"#ifdef BUILTIN_CLANG_DEFAULT_INCLUDE\n"
"#ifndef BPF_FUNCS_DEFINED\n"
"#define BPF_FUNCS_DEFINED\n"
"static void *(*bpf_map_lookup_elem)(void *, void *) = (void *)1;\n"
"static long (*bpf_map_update_elem)(void *, void *, void *, unsigned long) = (void *)2;\n"
"static long (*bpf_map_delete_elem)(void *, void *) = (void *)3;\n"
"static long (*bpf_probe_read)(void *, unsigned long, unsigned long) = (void *)4;\n"
"static long (*bpf_ktime_get_ns)(void) = (void *)5;\n"
"static long (*bpf_trace_printk)(void *, unsigned long, ...) = (void *)6;\n"
"static long (*bpf_get_prandom_u32)(void) = (void *)7;\n"
"static long (*bpf_get_smp_processor_id)(void) = (void *)8;\n"
"static long (*bpf_skb_store_bytes)(void *, unsigned long, void *, unsigned long, unsigned long) = (void *)9;\n"
"static long (*bpf_l3_csum_replace)(void *, unsigned long, unsigned long, unsigned long, unsigned long) = (void *)10;\n"
"static long (*bpf_l4_csum_replace)(void *, unsigned long, unsigned long, unsigned long, unsigned long) = (void *)11;\n"
"static void (*bpf_tail_call)(void *, void *, unsigned long) = (void *)12;\n"
"static long (*bpf_clone_redirect)(void *, unsigned long, unsigned long) = (void *)13;\n"
"static long (*bpf_get_current_pid_tgid)(void) = (void *)14;\n"
"static long (*bpf_get_current_uid_gid)(void) = (void *)15;\n"
"static long (*bpf_get_current_comm)(void *, unsigned long) = (void *)16;\n"
"static long (*bpf_get_cgroup_classid)(void *) = (void *)17;\n"
"static long (*bpf_skb_vlan_push)(void *, unsigned long, unsigned long) = (void *)18;\n"
"static long (*bpf_skb_vlan_pop)(void *) = (void *)19;\n"
"static long (*bpf_skb_get_tunnel_key)(void *, void *, unsigned long, unsigned long) = (void *)20;\n"
"static long (*bpf_skb_set_tunnel_key)(void *, void *, unsigned long, unsigned long) = (void *)21;\n"
"static long (*bpf_perf_event_read)(void *, unsigned long) = (void *)22;\n"
"static long (*bpf_redirect)(unsigned long, unsigned long) = (void *)23;\n"
"static long (*bpf_get_route_realm)(void *) = (void *)24;\n"
"static long (*bpf_perf_event_output)(void *, void *, unsigned long, void *, unsigned long) = (void *)25;\n"
"static long (*bpf_skb_load_bytes)(void *, unsigned long, void *, unsigned long) = (void *)26;\n"
"static long (*bpf_get_stackid)(void *, void *, unsigned long) = (void *)27;\n"
"static long (*bpf_csum_diff)(void *, unsigned long, void *, unsigned long, unsigned long) = (void *)28;\n"
"static long (*bpf_skb_get_tunnel_opt)(void *, void *, unsigned long) = (void *)29;\n"
"static long (*bpf_skb_set_tunnel_opt)(void *, void *, unsigned long) = (void *)30;\n"
"static long (*bpf_skb_change_proto)(void *, unsigned long, unsigned long) = (void *)31;\n"
"static long (*bpf_skb_change_type)(void *, unsigned long) = (void *)32;\n"
"static long (*bpf_skb_under_cgroup)(void *, void *, unsigned long) = (void *)33;\n"
"static long (*bpf_get_hash_recalc)(void *) = (void *)34;\n"
"static long (*bpf_get_current_task)(void) = (void *)35;\n"
"static long (*bpf_probe_write_user)(unsigned long, void *, unsigned long) = (void *)36;\n"
"static long (*bpf_current_task_under_cgroup)(void *, unsigned long) = (void *)37;\n"
"static long (*bpf_skb_change_tail)(void *, unsigned long, unsigned long) = (void *)38;\n"
"static long (*bpf_skb_pull_data)(void *, unsigned long) = (void *)39;\n"
"static long (*bpf_csum_update)(void *, unsigned long) = (void *)40;\n"
"static long (*bpf_set_hash_invalid)(void *) = (void *)41;\n"
"#endif\n"
"#endif\n"
;
