#
# Makefile for shared networking code called/used by IPv4 and IPv6
#
# Note: Currently this only contains the shared part of the TCP Implementation
#   a lot of the shared code still resides in net/ipv4/

obj-y     := tcp/
