#ifndef _UAPI_UFSHCI_H
#define _UAPI_UFSHCI_H

enum {
	UFSHCD_AHIBERN8_SCALE_1US	= 0,
	UFSHCD_AHIBERN8_SCALE_10US	= 1,
	UFSHCD_AHIBERN8_SCALE_100US	= 2,
	UFSHCD_AHIBERN8_SCALE_1MS	= 3,
	UFSHCD_AHIBERN8_SCALE_10MS	= 4,
	UFSHCD_AHIBERN8_SCALE_100MS	= 5,
	UFSHCD_AHIBERN8_SCALE_MAX,
};

#define UFSHCD_AHIBERN8_TIMER_MASK		0x03ff
#define UFSHCD_AHIBERN8_SCALE_MASK		0x1C00

#endif
