
vgpu-y := vgpu-core.o vgpu-sysfs.o vgpu-driver.o

obj-$(CONFIG_VGPU)			+= vgpu.o
obj-$(CONFIG_VGPU_VFIO)                 += vgpu_vfio.o
obj-$(CONFIG_VFIO_IOMMU_TYPE1_VGPU)     += vfio_iommu_type1_vgpu.o
