obj-$(CONFIG_INTEL_FPGA_PCI) += intel-fpga-pci.o
obj-$(CONFIG_INTEL_FPGA_FME) += intel-fpga-fme.o
obj-$(CONFIG_INTEL_FPGA_AFU) += intel-fpga-afu.o

intel-fpga-pci-objs := pcie.o feature-dev.o
intel-fpga-fme-objs := fme-main.o fme-pr.o
intel-fpga-afu-objs := afu-main.o afu-region.o afu-dma-region.o
