obj-$(CONFIG_AMD_SP) += ccp.o
ccp-objs := sp-dev.o sp-platform.o
ccp-$(CONFIG_PCI) += sp-pci.o

ccp-$(CONFIG_AMD_CCP) += ccp-dev.o \
	    ccp-dev-v3.o \
	    ccp-dev-v5.o \
	    ccp-ops.o \
	    ccp-dmaengine.o
