obj-$(CONFIG_SENSORS_IBM_OCC_P8_I2C) += hwmon_occ_p8.o
obj-$(CONFIG_SENSORS_IBM_OCC_P9) += hwmon_occ_p9.o

hwmon_occ_p8-objs := occ.o occ_sysfs.o occ_scom_i2c.o occ_p8.o occ_p8_i2c.o
hwmon_occ_p9-objs := occ.o occ_sysfs.o occ_p9.o
