#ifndef __DT_ADAU17X1_H
#define __DT_ADAU17X1_H

#define MICBIAS_0_90_AVDD		0
#define MICBIAS_0_65_AVDD		1

#define OUTPUT_MODE_HEADPHONE		0
#define OUTPUT_MODE_HEADPHONE_CAPLESS	1
#define OUTPUT_MODE_LINE		2

#define JACKDETECT_ACTIVE_HI		0
#define JACKDETECT_ACTIVE_LO		1

#endif
