#!/usr/bin/env python

# this testcase launches an IP packet with ttl=2. An input
# rule should capture the packet and increment the counter which
# we will then grep to know about the result

import os
from subprocess import call
try:
	from scapy.all import *
except ImportError:
	sys.stderr.write("Unable to import scapy")
	exit(0)

# config
nft = os.environ['NFT']
conf.L3socket = L3RawSocket

# capturing ruleset
call([nft + " add table ip t"], shell=True)
call([nft + " add chain ip t c {type filter hook input priority 0 \; policy accept \;}"], shell=True)
call([nft + " add rule ip t c ip ttl 2 counter"], shell = True)

# scapy packet
pkt = IP()
pkt.ttl = 2
sr1(pkt, verbose=False)

# results
ruleset = call([nft + " list ruleset | grep \"ip ttl 2 counter packets 1\" >/dev/null"], shell=True)
if ruleset != 0:
	sys.stderr.write("Packet not captured by nftables?")
	exit(1)
