obj-$(CONFIG_ARCH_LPC18XX)	+= clk-lpc18xx-cgu.o
obj-$(CONFIG_ARCH_LPC18XX)	+= clk-lpc18xx-ccu.o
obj-$(CONFIG_ARCH_LPC18XX)	+= clk-lpc18xx-creg.o
obj-$(CONFIG_ARCH_LPC32XX)	+= clk-lpc32xx.o
obj-$(CONFIG_CLK_74AUP1G157GW)	+= clk-74aup1g157gw.o
