#define MAS_VIDEO				0
#define MAS_JPEG				1
#define MAS_VFE					2
#define MAS_MDP					3
#define MAS_QDSS_BAM				4
#define MAS_SNOC_CFG				5
#define MAS_QDSS_ETR				6
#define MM_INT_0				7
#define MM_INT_1				8
#define MM_INT_2				9
#define MM_INT_BIMC				10
#define SNOC_INT_0				11
#define SNOC_INT_1				12
#define SNOC_INT_BIMC				13
#define SNOC_BIMC_0_MAS				14
#define SNOC_BIMC_1_MAS				15
#define QDSS_INT				16
#define BIMC_SNOC_SLV				17
#define SNOC_PNOC_MAS				18
#define PNOC_SNOC_SLV				19
#define SLV_SRVC_SNOC				20
#define SLV_QDSS_STM				21
#define SLV_IMEM				22
#define SLV_APSS				23
#define SLV_CATS_0				24
#define SLV_CATS_1				25

#define MAS_APPS				0
#define MAS_TCU0				1
#define MAS_TCU1				2
#define MAS_GFX					3
#define BIMC_SNOC_MAS				4
#define SNOC_BIMC_0_SLV				5
#define SNOC_BIMC_1_SLV				6
#define SLV_EBI_CH0				7
#define SLV_APPS_L2				8

#define SNOC_PNOC_SLV				0
#define PNOC_INT_0				1
#define PNOC_INT_1				2
#define PNOC_M_0				3
#define PNOC_M_1				4
#define PNOC_S_0				5
#define PNOC_S_1				6
#define PNOC_S_2				7
#define PNOC_S_3				8
#define PNOC_S_4				9
#define PNOC_S_8				10
#define PNOC_S_9				11
#define SLV_IMEM_CFG				12
#define SLV_CRYPTO_0_CFG			13
#define SLV_MSG_RAM				14
#define SLV_PDM					15
#define SLV_PRNG				16
#define SLV_CLK_CTL				17
#define SLV_MSS					18
#define SLV_TLMM				19
#define SLV_TCSR				20
#define SLV_SECURITY				21
#define SLV_SPDM				22
#define SLV_PNOC_CFG				23
#define SLV_PMIC_ARB				24
#define SLV_BIMC_CFG				25
#define SLV_BOOT_ROM				26
#define SLV_MPM					27
#define SLV_QDSS_CFG				28
#define SLV_RBCPR_CFG				29
#define SLV_SNOC_CFG				30
#define SLV_DEHR_CFG				31
#define SLV_VENUS_CFG				32
#define SLV_DISPLAY_CFG				33
#define SLV_CAMERA_CFG				34
#define SLV_USB_HS				35
#define SLV_SDCC_1				36
#define SLV_BLSP_1				37
#define SLV_SDCC_2				38
#define SLV_GFX_CFG				39
#define SLV_AUDIO				40
#define MAS_BLSP_1				41
#define MAS_SPDM				42
#define MAS_DEHR				43
#define MAS_AUDIO				44
#define MAS_USB_HS				45
#define MAS_PNOC_CRYPTO_0			46
#define MAS_PNOC_SDCC_1				47
#define MAS_PNOC_SDCC_2				48
#define PNOC_SNOC_MAS				49
