obj-$(CONFIG_CLK_UNIPHIER)	+= clk-uniphier.o
clk-uniphier-y			+= clk-uniphier-core.o
clk-uniphier-y			+= clk-uniphier-fixed-factor.o
clk-uniphier-y			+= clk-uniphier-fixed-rate.o
clk-uniphier-y			+= clk-uniphier-gate.o
clk-uniphier-y			+= clk-uniphier-mux.o
