/*
 * Copyright (c) 2016 Hisilicon Limited.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef _HNS_ROCE_COMMON_H
#define _HNS_ROCE_COMMON_H

#ifndef assert
#define assert(cond)
#endif

#define roce_writel(value, addr)     writel((value), (addr))
#define roce_readl(addr)            readl((addr))
#define roce_raw_write(value, addr) \
	__raw_writel((__force u32)cpu_to_le32(value), (addr))

#define roce_get_field(origin, mask, shift) \
	(((origin) & (mask)) >> (shift))

#define roce_get_bit(origin, shift) \
	roce_get_field((origin), (1ul << (shift)), (shift))

#define roce_set_field(origin, mask, shift, val) \
	do { \
		(origin) &= (~(mask)); \
		(origin) |= (((val) << (shift)) & (mask)); \
	} while (0)

#define roce_set_bit(origin, shift, val) \
	roce_set_field((origin), (1ul << (shift)), (shift), (val))

#define ROCEE_GLB_CFG_ROCEE_DB_SQ_MODE_S 3

#define ROCEE_GLB_CFG_ROCEE_DB_OTH_MODE_S 4

#define ROCEE_GLB_CFG_SQ_EXT_DB_MODE_S 5

#define ROCEE_GLB_CFG_OTH_EXT_DB_MODE_S 6

#define ROCEE_GLB_CFG_ROCEE_PORT_ST_S 10
#define ROCEE_GLB_CFG_ROCEE_PORT_ST_M  \
	(((1UL << 6) - 1) << ROCEE_GLB_CFG_ROCEE_PORT_ST_S)

#define ROCEE_GLB_CFG_TRP_RAQ_DROP_EN_S 16

#define ROCEE_DMAE_USER_CFG1_ROCEE_STREAM_ID_TB_CFG_S 0
#define ROCEE_DMAE_USER_CFG1_ROCEE_STREAM_ID_TB_CFG_M  \
	(((1UL << 24) - 1) << ROCEE_DMAE_USER_CFG1_ROCEE_STREAM_ID_TB_CFG_S)

#define ROCEE_DMAE_USER_CFG1_ROCEE_CACHE_TB_CFG_S 24
#define ROCEE_DMAE_USER_CFG1_ROCEE_CACHE_TB_CFG_M  \
	(((1UL << 4) - 1) << ROCEE_DMAE_USER_CFG1_ROCEE_CACHE_TB_CFG_S)

#define ROCEE_DMAE_USER_CFG2_ROCEE_STREAM_ID_PKT_CFG_S 0
#define ROCEE_DMAE_USER_CFG2_ROCEE_STREAM_ID_PKT_CFG_M   \
	(((1UL << 24) - 1) << ROCEE_DMAE_USER_CFG2_ROCEE_STREAM_ID_PKT_CFG_S)

#define ROCEE_DMAE_USER_CFG2_ROCEE_CACHE_PKT_CFG_S 24
#define ROCEE_DMAE_USER_CFG2_ROCEE_CACHE_PKT_CFG_M   \
	(((1UL << 4) - 1) << ROCEE_DMAE_USER_CFG2_ROCEE_CACHE_PKT_CFG_S)

#define ROCEE_CAEP_CEQ_AEQ_WL_CAEP_AEQ_WL_S 0
#define ROCEE_CAEP_CEQ_AEQ_WL_CAEP_AEQ_WL_M   \
	(((1UL << 16) - 1) << ROCEE_CAEP_CEQ_AEQ_WL_CAEP_AEQ_WL_S)

#define ROCEE_CAEP_CEQ_AEQ_WL_CAEP_CEQ_WL_S 16
#define ROCEE_CAEP_CEQ_AEQ_WL_CAEP_CEQ_WL_M   \
	(((1UL << 16) - 1) << ROCEE_CAEP_CEQ_AEQ_WL_CAEP_CEQ_WL_S)

#define ROCEE_DB_SQ_WL_ROCEE_DB_SQ_WL_S 0
#define ROCEE_DB_SQ_WL_ROCEE_DB_SQ_WL_M   \
	(((1UL << 16) - 1) << ROCEE_DB_SQ_WL_ROCEE_DB_SQ_WL_S)

#define ROCEE_DB_SQ_WL_ROCEE_DB_SQ_WL_EMPTY_S 16
#define ROCEE_DB_SQ_WL_ROCEE_DB_SQ_WL_EMPTY_M   \
	(((1UL << 16) - 1) << ROCEE_DB_SQ_WL_ROCEE_DB_SQ_WL_EMPTY_S)

#define ROCEE_DB_OTHERS_WL_ROCEE_DB_OTH_WL_S 0
#define ROCEE_DB_OTHERS_WL_ROCEE_DB_OTH_WL_M   \
	(((1UL << 16) - 1) << ROCEE_DB_OTHERS_WL_ROCEE_DB_OTH_WL_S)

#define ROCEE_DB_OTHERS_WL_ROCEE_DB_OTH_WL_EMPTY_S 16
#define ROCEE_DB_OTHERS_WL_ROCEE_DB_OTH_WL_EMPTY_M   \
	(((1UL << 16) - 1) << ROCEE_DB_OTHERS_WL_ROCEE_DB_OTH_WL_EMPTY_S)

#define ROCEE_RAQ_WL_ROCEE_RAQ_WL_S 0
#define ROCEE_RAQ_WL_ROCEE_RAQ_WL_M   \
	(((1UL << 8) - 1) << ROCEE_RAQ_WL_ROCEE_RAQ_WL_S)

#define ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_POL_TIME_INTERVAL_S 0
#define ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_POL_TIME_INTERVAL_M   \
	(((1UL << 15) - 1) << \
	ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_POL_TIME_INTERVAL_S)

#define ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_RAQ_TIMEOUT_CHK_CFG_S 16
#define ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_RAQ_TIMEOUT_CHK_CFG_M   \
	(((1UL << 4) - 1) << \
	ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_RAQ_TIMEOUT_CHK_CFG_S)

#define ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_RAQ_TIMEOUT_CHK_EN_S 20

#define ROCEE_WRMS_POL_TIME_INTERVAL_WRMS_EXT_RAQ_MODE 21

#define ROCEE_EXT_DB_SQ_H_EXT_DB_SQ_SHIFT_S 0
#define ROCEE_EXT_DB_SQ_H_EXT_DB_SQ_SHIFT_M   \
	(((1UL << 5) - 1) << ROCEE_EXT_DB_SQ_H_EXT_DB_SQ_SHIFT_S)

#define ROCEE_EXT_DB_SQ_H_EXT_DB_SQ_BA_H_S 5
#define ROCEE_EXT_DB_SQ_H_EXT_DB_SQ_BA_H_M   \
	(((1UL << 5) - 1) << ROCEE_EXT_DB_SQ_H_EXT_DB_SQ_BA_H_S)

#define ROCEE_EXT_DB_OTH_H_EXT_DB_OTH_SHIFT_S 0
#define ROCEE_EXT_DB_OTH_H_EXT_DB_OTH_SHIFT_M   \
	(((1UL << 5) - 1) << ROCEE_EXT_DB_OTH_H_EXT_DB_OTH_SHIFT_S)

#define ROCEE_EXT_DB_SQ_H_EXT_DB_OTH_BA_H_S 5
#define ROCEE_EXT_DB_SQ_H_EXT_DB_OTH_BA_H_M   \
	(((1UL << 5) - 1) << ROCEE_EXT_DB_SQ_H_EXT_DB_OTH_BA_H_S)

#define ROCEE_EXT_RAQ_H_EXT_RAQ_SHIFT_S 0
#define ROCEE_EXT_RAQ_H_EXT_RAQ_SHIFT_M   \
	(((1UL << 5) - 1) << ROCEE_EXT_RAQ_H_EXT_RAQ_SHIFT_S)

#define ROCEE_EXT_RAQ_H_EXT_RAQ_BA_H_S 8
#define ROCEE_EXT_RAQ_H_EXT_RAQ_BA_H_M   \
	(((1UL << 5) - 1) << ROCEE_EXT_RAQ_H_EXT_RAQ_BA_H_S)

#define ROCEE_CAEP_CE_BURST_NUM_CFG_CAEP_CE_BURST_NUM_CFG_S 0
#define ROCEE_CAEP_CE_BURST_NUM_CFG_CAEP_CE_BURST_NUM_CFG_M   \
	(((1UL << 16) - 1) << \
	ROCEE_CAEP_CE_BURST_NUM_CFG_CAEP_CE_BURST_NUM_CFG_S)

#define ROCEE_CAEP_CE_BURST_NUM_CFG_CAEP_CE_INTERVAL_MIN_S 16
#define ROCEE_CAEP_CE_BURST_NUM_CFG_CAEP_CE_INTERVAL_MIN_M   \
	(((1UL << 16) - 1) << \
	ROCEE_CAEP_CE_BURST_NUM_CFG_CAEP_CE_INTERVAL_MIN_S)

#define ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_WEIGTH_S 0
#define ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_WEIGTH_M   \
	(((1UL << 16) - 1) << \
	ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_WEIGTH_S)

#define ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_PORT_S 16
#define ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_PORT_M   \
	(((1UL << 4) - 1) << ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_PORT_S)

#define ROCEE_TSP_RR_CFG_ROCEE_TSP_SL_SP_EN_S 20

#define ROCEE_TSP_RR_CFG_ROCEE_TSP_WA_SP_PORT_S 21
#define ROCEE_TSP_RR_CFG_ROCEE_TSP_WA_SP_PORT_M   \
	(((1UL << 2) - 1) << ROCEE_TSP_RR_CFG_ROCEE_TSP_WA_SP_PORT_S)

#define ROCEE_TSP_RR_CFG_ROCEE_TSP_WA_SP_EN_S 23

#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_IN_MDF_S 0
#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_IN_MDF_M   \
	(((1UL << 19) - 1) << ROCEE_BT_CMD_H_ROCEE_BT_CMD_IN_MDF_S)

#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_S 19

#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_MDF_S 20
#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_MDF_M   \
	(((1UL << 2) - 1) << ROCEE_BT_CMD_H_ROCEE_BT_CMD_MDF_S)

#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_BA_H_S 22
#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_BA_H_M   \
	(((1UL << 5) - 1) << ROCEE_BT_CMD_H_ROCEE_BT_CMD_BA_H_S)

#define ROCEE_BT_CMD_H_ROCEE_BT_CMD_HW_SYNS_S 31

#define ROCEE_QP1C_CFG0_0_ROCEE_QP1C_QP_ST_S 0
#define ROCEE_QP1C_CFG0_0_ROCEE_QP1C_QP_ST_M   \
	(((1UL << 3) - 1) << ROCEE_QP1C_CFG0_0_ROCEE_QP1C_QP_ST_S)

#define ROCEE_QP1C_CFG3_0_ROCEE_QP1C_RQ_HEAD_S 0
#define ROCEE_QP1C_CFG3_0_ROCEE_QP1C_RQ_HEAD_M   \
	(((1UL << 15) - 1) << ROCEE_QP1C_CFG3_0_ROCEE_QP1C_RQ_HEAD_S)

#define ROCEE_MB6_ROCEE_MB_CMD_S 0
#define ROCEE_MB6_ROCEE_MB_CMD_M   \
	(((1UL << 8) - 1) << ROCEE_MB6_ROCEE_MB_CMD_S)

#define ROCEE_MB6_ROCEE_MB_CMD_MDF_S 8
#define ROCEE_MB6_ROCEE_MB_CMD_MDF_M   \
	(((1UL << 4) - 1) << ROCEE_MB6_ROCEE_MB_CMD_MDF_S)

#define ROCEE_MB6_ROCEE_MB_EVENT_S 14

#define ROCEE_MB6_ROCEE_MB_HW_RUN_S 15

#define ROCEE_MB6_ROCEE_MB_TOKEN_S 16
#define ROCEE_MB6_ROCEE_MB_TOKEN_M   \
	(((1UL << 16) - 1) << ROCEE_MB6_ROCEE_MB_TOKEN_S)

#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_INP_H_S 0
#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_INP_H_M   \
	(((1UL << 24) - 1) << ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_INP_H_S)

#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_CMD_MDF_S 24
#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_CMD_MDF_M   \
	(((1UL << 4) - 1) << ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_CMD_MDF_S)

#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_CMD_S 28
#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_CMD_M   \
	(((1UL << 3) - 1) << ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_CMD_S)

#define ROCEE_DB_OTHERS_H_ROCEE_DB_OTH_HW_SYNS_S 31

#define ROCEE_SMAC_H_ROCEE_SMAC_H_S 0
#define ROCEE_SMAC_H_ROCEE_SMAC_H_M   \
	(((1UL << 16) - 1) << ROCEE_SMAC_H_ROCEE_SMAC_H_S)

#define ROCEE_SMAC_H_ROCEE_PORT_MTU_S 16
#define ROCEE_SMAC_H_ROCEE_PORT_MTU_M   \
	(((1UL << 4) - 1) << ROCEE_SMAC_H_ROCEE_PORT_MTU_S)

#define ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQC_STATE_S 0
#define ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQC_STATE_M   \
	(((1UL << 2) - 1) << \
	ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQC_STATE_S)

#define ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQC_AEQE_SHIFT_S 8
#define ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQC_AEQE_SHIFT_M   \
	(((1UL << 4) - 1) << \
	ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQC_AEQE_SHIFT_S)

#define ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AE_IRQ_PEND_S 16

#define ROCEE_CAEP_AEQC_AEQE_SHIFT_CAEP_AEQ_ALM_OVF_INT_ST_S 17

#define ROCEE_CAEP_AEQE_CUR_IDX_CAEP_AEQ_BT_H_S 0
#define ROCEE_CAEP_AEQE_CUR_IDX_CAEP_AEQ_BT_H_M   \
	(((1UL << 5) - 1) << ROCEE_CAEP_AEQE_CUR_IDX_CAEP_AEQ_BT_H_S)

#define ROCEE_CAEP_AEQE_CUR_IDX_CAEP_AEQE_CUR_IDX_S 16
#define ROCEE_CAEP_AEQE_CUR_IDX_CAEP_AEQE_CUR_IDX_M   \
	(((1UL << 16) - 1) << \
	ROCEE_CAEP_AEQE_CUR_IDX_CAEP_AEQE_CUR_IDX_S)

#define ROCEE_CAEP_AEQE_CONS_IDX_CAEP_AEQE_CONS_IDX_S 0
#define ROCEE_CAEP_AEQE_CONS_IDX_CAEP_AEQE_CONS_IDX_M   \
	(((1UL << 16) - 1) << \
	ROCEE_CAEP_AEQE_CONS_IDX_CAEP_AEQE_CONS_IDX_S)

#define ROCEE_CAEP_CEQC_SHIFT_CAEP_CEQC_CEQE_SHIFT_S 8
#define ROCEE_CAEP_CEQC_SHIFT_CAEP_CEQC_CEQE_SHIFT_M   \
	(((1UL << 4) - 1) << ROCEE_CAEP_CEQC_SHIFT_CAEP_CEQC_CEQE_SHIFT_S)

#define ROCEE_CAEP_CEQC_SHIFT_CAEP_CEQ_ALM_OVF_INT_ST_S 16

#define ROCEE_CAEP_CEQC_SHIFT_CAEP_CE_IRQ_ST_S 30

#define ROCEE_CAEP_CEQC_CUR_IDX_CAEP_CEQE_CUR_IDX_S 16
#define ROCEE_CAEP_CEQC_CUR_IDX_CAEP_CEQE_CUR_IDX_M   \
	(((1UL << 16) - 1) << \
	ROCEE_CAEP_CEQC_CUR_IDX_CAEP_CEQE_CUR_IDX_S)

#define ROCEE_CAEP_CEQC_CONS_IDX_CAEP_CEQE_CONS_IDX_S 0
#define ROCEE_CAEP_CEQC_CONS_IDX_CAEP_CEQE_CONS_IDX_M   \
	(((1UL << 16) - 1) << \
	ROCEE_CAEP_CEQC_CONS_IDX_CAEP_CEQE_CONS_IDX_S)

#define ROCEE_CAEP_CE_IRQ_MASK_CAEP_CE_IRQ_MASK_S 0

#define ROCEE_CAEP_CE_IRQ_MASK_CAEP_CEQ_ALM_OVF_MASK_S 1

#define ROCEE_CAEP_CEQ_ALM_OVF_CAEP_CEQ_ALM_OVF_S 0

#define ROCEE_CAEP_AE_MASK_CAEP_AEQ_ALM_OVF_MASK_S 0

#define ROCEE_CAEP_AE_MASK_CAEP_AE_IRQ_MASK_S 1

#define ROCEE_CAEP_AE_ST_CAEP_AEQ_ALM_OVF_S 0

#define ROCEE_CAEP_AE_ST_CAEP_AE_IRQ_ST_S 1

#define ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_CNT_S 0
#define ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_CNT_M   \
	(((1UL << 16) - 1) << ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_CNT_S)

#define ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_TYPE_S 16
#define ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_TYPE_M   \
	(((1UL << 6) - 1) << ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_TYPE_S)

#define ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_EN_S 22
#define ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_EN_M   \
	(((1UL << 6) - 1) << ROCEE_TRP_RX_DROP_CFG_TRP_RX_DROP_EN_S)

#define ROCEE_SDB_ISSUE_PTR_SDB_ISSUE_PTR_S 0
#define ROCEE_SDB_ISSUE_PTR_SDB_ISSUE_PTR_M   \
	(((1UL << 28) - 1) << ROCEE_SDB_ISSUE_PTR_SDB_ISSUE_PTR_S)

#define ROCEE_SDB_SEND_PTR_SDB_SEND_PTR_S 0
#define ROCEE_SDB_SEND_PTR_SDB_SEND_PTR_M   \
	(((1UL << 28) - 1) << ROCEE_SDB_SEND_PTR_SDB_SEND_PTR_S)

#define ROCEE_DB_SQ_ST_ROCEE_DB_SQ_ALM_OVF_S 0

#define ROCEE_DB_SQ_ST_ROCEE_DB_SQ_OV_S 1

#define ROCEE_DB_SQ_ST_ROCEE_DB_SQ_ALM_EMPTY_S 2

#define ROCEE_DB_OTHERS_ST_ROCEE_DB_OTH_ALM_OVF_S 0

#define ROCEE_DB_OTHERS_ST_ROCEE_DB_OTH_OV_S 1

#define ROCEE_DB_OTHERS_ST_ROCEE_DB_OTH_ALM_EMPTY_S 2

#define ROCEE_EXT_DB_ALM_SQ_BRESP_ERR_ST_S 0
#define ROCEE_EXT_DB_ALM_SQ_BRESP_ERR_ST_M   \
	(((1UL << 3) - 1) << ROCEE_EXT_DB_ALM_SQ_BRESP_ERR_ST_S)

#define ROCEE_EXT_DB_ALM_SQ_RRESP_ERR_ST_S 3
#define ROCEE_EXT_DB_ALM_SQ_RRESP_ERR_ST_M   \
	(((1UL << 3) - 1) << ROCEE_EXT_DB_ALM_SQ_RRESP_ERR_ST_S)

#define ROCEE_EXT_DB_ALM_SQ_CMD_XOFF_S 6

#define ROCEE_EXT_DB_ALM_OTH_BRESP_ERR_ST_S 8
#define ROCEE_EXT_DB_ALM_OTH_BRESP_ERR_ST_M   \
	(((1UL << 3) - 1) << ROCEE_EXT_DB_ALM_OTH_BRESP_ERR_ST_S)

#define ROCEE_EXT_DB_ALM_OTH_RRESP_ERR_ST_S 11
#define ROCEE_EXT_DB_ALM_OTH_RRESP_ERR_ST_M   \
	(((1UL << 3) - 1) << ROCEE_EXT_DB_ALM_OTH_RRESP_ERR_ST_S)

#define ROCEE_EXT_DB_ALM_OTH_CMD_XOFF_S 14

#define ROCEE_EXT_DB_ALM_RAQ_BRESP_ERR_ST_S 16
#define ROCEE_EXT_DB_ALM_RAQ_BRESP_ERR_ST_M   \
	(((1UL << 3) - 1) << ROCEE_EXT_DB_ALM_RAQ_BRESP_ERR_ST_S)

#define ROCEE_EXT_DB_ALM_RAQ_RRESP_ERR_ST_S 19
#define ROCEE_EXT_DB_ALM_RAQ_RRESP_ERR_ST_M   \
	(((1UL << 3) - 1) << ROCEE_EXT_DB_ALM_RAQ_RRESP_ERR_ST_S)

#define ROCEE_CQ_MAX_ROCEE_CQ_MAX_S 0
#define ROCEE_CQ_MAX_ROCEE_CQ_MAX_M   \
	(((1UL << 16) - 1) << ROCEE_CQ_MAX_ROCEE_CQ_MAX_S)

#define ROCEE_CQ_MAX_ROCEE_CQ_MAX_VLD_S 31

#define ROCEE_MR_MAX_ROCEE_MR_MAX_S 0
#define ROCEE_MR_MAX_ROCEE_MR_MAX_M   \
	(((1UL << 24) - 1) << ROCEE_MR_MAX_ROCEE_MR_MAX_S)

#define ROCEE_MR_MAX_ROCEE_MR_MAX_VLD_S 31

#define ROCEE_QP_MAX_ROCEE_QP_MAX_S 0
#define ROCEE_QP_MAX_ROCEE_QP_MAX_M   \
	(((1UL << 24) - 1) << ROCEE_QP_MAX_ROCEE_QP_MAX_S)

#define ROCEE_SDB_INV_CNT_SDB_INV_CNT_S 0
#define ROCEE_SDB_INV_CNT_SDB_INV_CNT_M   \
	(((1UL << 16) - 1) << ROCEE_SDB_INV_CNT_SDB_INV_CNT_S)

#define ROCEE_QMM_CACHE_CLR_QPC_CACHE_UNCLR_S 0

#define ROCEE_QMM_CACHE_CLR_MTPT_CACHE_UNCLR_S 1

#define ROCEE_QMM_CACHE_CLR_CQC_CACHE_UNCLR_S 2

#define ROCEE_QMM_CACHE_REFRESH_QPC_CACHE_REFRESH_S 0

#define ROCEE_QMM_CACHE_REPLACE_QPC_CACHE_REPLACE_S 0

#define AM_CTRL_GLOBAL_CTRL_LAT_STAT_RD_EN_S 1
#define AM_CTRL_GLOBAL_CTRL_LAT_STAT_WR_EN_S 2

#define AM_CTRL_LATENCY_SEL_CTRL_LAT_RD_PORT_SEL_S 0
#define AM_CTRL_LATENCY_SEL_CTRL_LAT_RD_PORT_SEL_M   \
	(((1UL << 4) - 1) << \
	AM_CTRL_LATENCY_SEL_CTRL_LAT_RD_PORT_SEL_S)

#define AM_CTRL_LATENCY_SEL_CTRL_LAT_WR_PORT_SEL_S 8
#define AM_CTRL_LATENCY_SEL_CTRL_LAT_WR_PORT_SEL_M   \
	(((1UL << 4) - 1) << \
	AM_CTRL_LATENCY_SEL_CTRL_LAT_WR_PORT_SEL_S)

#define AM_CFG_MAX_TRANS_CFG_MAX_RD_TRANS_S 0
#define AM_CFG_MAX_TRANS_CFG_MAX_RD_TRANS_M   \
	(((1UL << 7) - 1) << AM_CFG_MAX_TRANS_CFG_MAX_RD_TRANS_S)

#define AM_CFG_MAX_TRANS_CFG_MAX_WR_TRANS_S 8
#define AM_CFG_MAX_TRANS_CFG_MAX_WR_TRANS_M   \
	(((1UL << 7) - 1) << AM_CFG_MAX_TRANS_CFG_MAX_WR_TRANS_S)

#define AM_CFG_SINGLE_PORT_MAX_TRANS_CFG_MAX_SGL_PORT_RD_TRANS_S 0
#define AM_CFG_SINGLE_PORT_MAX_TRANS_CFG_MAX_SGL_PORT_RD_TRANS_M   \
	(((1UL << 7) - 1) << \
	AM_CFG_SINGLE_PORT_MAX_TRANS_CFG_MAX_SGL_PORT_RD_TRANS_S)

#define AM_CFG_SINGLE_PORT_MAX_TRANS_CFG_MAX_SGL_PORT_WR_TRANS_S 8
#define AM_CFG_SINGLE_PORT_MAX_TRANS_CFG_MAX_SGL_PORT_WR_TRANS_M   \
	(((1UL << 7) - 1) << \
	AM_CFG_SINGLE_PORT_MAX_TRANS_CFG_MAX_SGL_PORT_WR_TRANS_S)

#define AM_CURR_PORT_STS_CURR_RD_PORT_STS_S 0
#define AM_CURR_PORT_STS_CURR_RD_PORT_STS_M   \
	(((1UL << 16) - 1) << AM_CURR_PORT_STS_CURR_RD_PORT_STS_S)

#define AM_CURR_PORT_STS_CURR_WR_PORT_STS_S 16
#define AM_CURR_PORT_STS_CURR_WR_PORT_STS_M   \
	(((1UL << 16) - 1) << AM_CURR_PORT_STS_CURR_WR_PORT_STS_S)

#define ROCEE_TSP_DROP_CFG0_TSP_DROP_INTERVAL_CFG_S 0
#define ROCEE_TSP_DROP_CFG0_TSP_DROP_INTERVAL_CFG_M   \
	(((1UL << 24) - 1) << ROCEE_TSP_DROP_CFG0_TSP_DROP_INTERVAL_CFG_S)

#define ROCEE_TSP_DROP_CFG0_TSP_DROP_NUM_CFG_S 24
#define ROCEE_TSP_DROP_CFG0_TSP_DROP_NUM_CFG_M   \
	(((1UL << 8) - 1) << ROCEE_TSP_DROP_CFG0_TSP_DROP_NUM_CFG_S)

#define ROCEE_TSP_DROP_CFG1_TSP_DROP_EN_S 0
#define ROCEE_TSP_DROP_CFG1_TSP_DROP_EN_M   \
	(((1UL << 5) - 1) << ROCEE_TSP_DROP_CFG1_TSP_DROP_EN_S)

#define ROCEE_TSP_DROP_CFG1_TSP_DROP_MODE_S 7

#define SBM_ROCEE_CFG_REG_SBM_CFG_EN_ROCEE_S 1
#define SBM_ROCEE_CFG_REG_SBM_CFG_CRD_EN_ROCEE_S 2

#define ROCE_DEV_IOBASE				(0xc4000000)

/**********ROCEE_REG DEFINITION****************/

#define ROCEE_VENDOR_ID_REG			0x0
#define ROCEE_VENDOR_PART_ID_REG		0x4

#define ROCEE_HW_VERSION_REG			0x8

#define ROCEE_SYS_IMAGE_GUID_L_REG		0xC
#define ROCEE_SYS_IMAGE_GUID_H_REG		0x10

#define ROCEE_PORT_MSG_SIZE_REG			0x4C

#define ROCEE_PORT_GID_L_0_REG			0x50
#define ROCEE_PORT_GID_ML_0_REG			0x54
#define ROCEE_PORT_GID_MH_0_REG			0x58
#define ROCEE_PORT_GID_H_0_REG			0x5C

#define ROCEE_BT_CMD_H_REG			0x204

#define ROCEE_SMAC_L_0_REG			0x240
#define ROCEE_SMAC_H_0_REG			0x244

#define ROCEE_QP1C_CFG3_0_REG			0x27C

#define ROCEE_CAEP_AEQE_CONS_IDX_REG		0x3AC
#define ROCEE_CAEP_CEQC_CONS_IDX_0_REG		0x3BC

#define ROCEE_ECC_UCERR_ALM1_REG		0xB38
#define ROCEE_ECC_UCERR_ALM2_REG		0xB3C

#define ROCEE_ECC_CERR_ALM1_REG			0xB44
#define ROCEE_ECC_CERR_ALM2_REG			0xB48

#define ROCEE_ACK_DELAY_REG			0x14
#define ROCEE_GLB_CFG_REG			0x18

#define ROCEE_DMAE_USER_CFG0_REG		0x3C
#define ROCEE_DMAE_USER_CFG1_REG		0x40
#define ROCEE_DMAE_USER_CFG2_REG		0x44
#define ROCEE_DMAE_USER_CFG3_REG		0x48

#define ROCEE_DB_SQ_WL_REG			0x154
#define ROCEE_DB_OTHERS_WL_REG			0x158
#define ROCEE_RAQ_WL_REG			0x15C
#define ROCEE_WRMS_POL_TIME_INTERVAL_REG	0x160
#define ROCEE_EXT_DB_SQ_REG			0x164
#define ROCEE_EXT_DB_SQ_H_REG			0x168
#define ROCEE_EXT_DB_OTH_REG			0x16C

#define ROCEE_EXT_DB_OTH_H_REG			0x170
#define ROCEE_EXT_DB_SQ_WL_EMPTY_REG		0x174
#define ROCEE_EXT_DB_SQ_WL_REG			0x178
#define ROCEE_EXT_DB_OTHERS_WL_EMPTY_REG	0x17C
#define ROCEE_EXT_DB_OTHERS_WL_REG		0x180
#define ROCEE_EXT_RAQ_REG			0x184
#define ROCEE_EXT_RAQ_H_REG			0x188

#define ROCEE_CAEP_CE_INTERVAL_CFG_REG		0x190
#define ROCEE_CAEP_CE_BURST_NUM_CFG_REG		0x194
#define ROCEE_QMM_TB_CFG_REG			0x198
#define ROCEE_TSP_RR_CFG_REG			0x19C
#define ROCEE_BT_CMD_L_REG			0x200

#define ROCEE_MB1_REG				0x210
#define ROCEE_MB2_REG				0x214
#define ROCEE_MB3_REG				0x218
#define ROCEE_MB4_REG				0x21C
#define ROCEE_MB5_REG				0x220
#define ROCEE_MB6_REG				0x224
#define ROCEE_MB7_REG				0x228
#define ROCEE_DB_SQ_L_0_REG			0x230
#define ROCEE_DB_SQ_H_0_REG			0x234

#define ROCEE_DB_OTHERS_L_0_REG			0x238
#define ROCEE_DB_OTHERS_H_0_REG			0x23C

#define ROCEE_QP1C_CFG0_0_REG			0x270

#define ROCEE_CAEP_AEQC_AEQE_SHIFT_REG		0x3A0
#define ROCEE_CAEP_CEQC_SHIFT_0_REG		0x3B0

#define ROCEE_CAEP_CE_IRQ_MASK_0_REG		0x3C0

#define ROCEE_CAEP_CEQ_ALM_OVF_0_REG		0x3C4

#define ROCEE_CAEP_AE_MASK_REG			0x6C8
#define ROCEE_CAEP_AE_ST_REG			0x6CC
#define ROCEE_TRP_RX_DROP_CFG_REG		0x6D0
#define ROCEE_ODB_DEPTH_REG			0x700
#define ROCEE_TSQ_DEPTH_REG			0x704
#define ROCEE_RAQ_DEPTH_REG			0x708

#define ROCEE_DB_QUE_ST0_REG			0x750
#define ROCEE_DB_QUE_ST1_REG			0x754
#define ROCEE_SDB_ISSUE_PTR_REG			0x758
#define ROCEE_SDB_SEND_PTR_REG			0x75C
#define ROCEE_EXT_SQ_ST0_REG			0x760
#define ROCEE_EXT_SQ_ST1_REG			0x764
#define ROCEE_EXT_RAQ_ST0_REG			0x768
#define ROCEE_EXT_RAQ_ST1_REG			0x76C
#define ROCEE_WRMS_ACKQ_OVF_FLG_REG		0x770
#define ROCEE_DB_SQ_ST_REG			0x774
#define ROCEE_DB_OTHERS_ST_REG			0x778
#define ROCEE_EXT_DB_ALM_REG			0x77C
#define ROCEE_CQ_MAX_REG			0x780
#define ROCEE_MR_MAX_REG			0x784
#define ROCEE_QP_MAX_REG			0x788
#define ROCEE_RETRY_QP_CNT_REG			0x78C
#define ROCEE_WRMS_RETY_HDK_REG			0x794
#define ROCEE_WRMS_MEM_INIT_RDY_REG		0x798
#define ROCEE_DIRECT_WQE_ST_REG			0x79C
#define ROCEE_TSP_THC_LL_REG			0x7A0
#define ROCEE_TSP_CREDIT_CNT0_REG		0x7A4
#define ROCEE_TSP_CREDIT_CNT1_REG		0x7A8

#define ROCEE_CAEP_WR_REQ_REG			0x818
#define ROCEE_TRP_ERR_PKT_CNT_0_REG		0x81C

#define ROCEE_TRP_INTERNAL_DATA_FIFO_EMPTY_REG	0x848
#define ROCEE_TRP_INTERNAL_DATA_FIFO_FULL_REG	0x84C
#define ROCEE_CAEP_INTERNAL_FIFO_FULL_REG	0x850
#define ROCEE_TRP_PIPE_FSM_REG			0x854
#define ROCEE_TRP_RX_PKT_CNT_0_REG		0x880

#define ROCEE_TRP_RX_UD_CNT_0_REG		0x898
#define ROCEE_TRP_RX_RC_CNT_0_REG		0x8B0

#define ROCEE_CAEP_CE_CNT_REG			0x8C8
#define ROCEE_CAEP_WR_CQE_CNT_REG		0x8D0
#define ROCEE_CAEP_AE_CNT_REG			0x8D4
#define ROCEE_MBX_ISSUE_CNT_REG			0x980
#define ROCEE_MBX_EXEC_CNT_REG			0x984
#define ROCEE_SDB_ISSUE_CNT_REG			0x988
#define ROCEE_SDB_ENQ_CNT_REG			0x98C
#define ROCEE_SDB_DEQ_CNT_REG			0x990
#define ROCEE_ODB_ISSUE_CNT_REG			0x994
#define ROCEE_ODB_ENQ_CNT_REG			0x998
#define ROCEE_ODB_DEQ_CNT_REG			0x99C
#define ROCEE_MBX_INV_CNT_REG			0x9A0
#define ROCEE_SDB_INV_CNT_REG			0x9A4
#define ROCEE_ODB_INV_CNT_REG			0x9A8
#define ROCEE_SDB_RETRY_CNT_REG			0x9AC
#define ROCEE_SDB_OV_CNT_REG			0x9B0
#define ROCEE_ODB_OV_CNT_REG			0x9B4
#define ROCEE_TRP_PKT_ERR_FLG_0_REG		0x9B8

#define ROCEE_TSP_HDK_ST_REG			0x9E8
#define ROCEE_TSP_BP_ST_REG			0x9EC
#define ROCEE_TSP_RETRY_CNT_REG			0x9F0
#define ROCEE_TSP_CSDB_DBBK_CNT_REG		0x9F4
#define ROCEE_TSP_TGM_CSDB_CNT_REG		0x9F8
#define ROCEE_TSP_P0_PKT_CNT_REG		0x9FC

#define ROCEE_AXI_ERR_ALM0_REG			0xB00
#define ROCEE_AXI_ERR_ALM1_REG			0xB04

#define ROCEE_ECC_UCERR_ALM0_REG		0xB34
#define ROCEE_ECC_CERR_ALM0_REG			0xB40

#define ROCEE_QMM_CHK_CMD_VLD_REG		0x1000
#define ROCEE_QMM_CFG_FIFO_LEVEL_REG		0x1004
#define ROCEE_QMM_QPC_MISS_CNT_REG		0x1010
#define ROCEE_QMM_QPC_HIT_CNT_REG		0x1014
#define ROCEE_QMM_QPC_REPLACE_IND_REG		0x1018
#define ROCEE_QMM_QPC_SRH_STATUS_REG		0x101C
#define ROCEE_QMM_QPC_SRH_TAG_REG		0x1020
#define ROCEE_QMM_MTPT_MISS_CNT_REG		0x1030
#define ROCEE_QMM_MTPT_HIT_CNT_REG		0x1034
#define ROCEE_QMM_MTPT_REPLACE_IND_REG		0x1038
#define ROCEE_QMM_MTPT_SRH_STATUS_REG		0x103C
#define ROCEE_QMM_MTPT_SRH_TAG_REG		0x1040
#define ROCEE_QMM_CQC_MISS_CNT_REG		0x1050
#define ROCEE_QMM_CQC_HIT_CNT_REG		0x1054
#define ROCEE_QMM_CQC_REPLACE_IND_REG		0x1058
#define ROCEE_QMM_CQC_SRH_STATUS_REG		0x105C
#define ROCEE_QMM_CQC_SRH_TAG_REG		0x1060
#define ROCEE_QPC_CACHE_RW_STATUS_REG		0x1070
#define ROCEE_MTPT_CACHE_RW_STATUS_REG		0x1074
#define ROCEE_CQC_CACHE_RW_STATUS_REG		0x1078
#define ROCEE_QMM_CACHE_CLR_REG			0x1080

#define ROCEE_QMM_CACHE_REFRESH_REG		0x1088
#define ROCEE_QPC_DMAE_STATUS_REG		0x108C
#define ROCEE_MTPT_DMAE_STATUS_REG		0x1090
#define ROCEE_CQC_DMAE_STATUS_REG		0x1094
#define ROCEE_QMM_CACHE_REPLACE_REG		0x1098
#define ROCEE_QMM_QPC_DIRTY0_REG		0x109C

#define ROCEE_QMM_MTPT_DIRTY0_REG		0x10AC
#define ROCEE_QMM_CQC_DIRTY0_REG		0x10B4

#define ROCEE_AXI_MST_A_DFX_REG			0xFC00
#define ROCEE_AXI_MST_B_DFX_REG			0xFE00

#define ROCEE_OOOA_CFG_BASE		(ROCEE_AXI_MST_A_DFX_REG)
#define ROCEE_OOOB_CFG_BASE		(ROCEE_AXI_MST_B_DFX_REG)

#define ROCEE_OOOA_CFG_AM_CTRL_GLOBAL_REG \
				(ROCEE_OOOA_CFG_BASE + 0x0)
#define ROCEE_OOOA_CFG_AM_CTRL_LATENCY_SEL_REG \
				(ROCEE_OOOA_CFG_BASE + 0x4)
#define ROCEE_OOOA_CFG_AM_CFG_MAX_TRANS_REG \
				(ROCEE_OOOA_CFG_BASE + 0x10)
#define ROCEE_OOOA_CFG_AM_CFG_SINGLE_PORT_MAX_TRANS_REG \
				(ROCEE_OOOA_CFG_BASE + 0x14)
#define ROCEE_OOOA_CFG_AM_CURR_PORT_STS_REG \
				(ROCEE_OOOA_CFG_BASE + 0x100)
#define ROCEE_OOOA_CFG_AM_CURR_ROB_ECC_ERR_REG \
				(ROCEE_OOOA_CFG_BASE + 0x10C)
#define ROCEE_OOOA_CFG_AM_CURR_MAX_RD_LATENCY_REG \
				(ROCEE_OOOA_CFG_BASE + 0x110)
#define ROCEE_OOOA_CFG_AM_CURR_AVA_RD_LATENCY_REG \
				(ROCEE_OOOA_CFG_BASE + 0x114)
#define ROCEE_OOOA_CFG_AM_CURR_RD_LATENCY_REG \
				(ROCEE_OOOA_CFG_BASE + 0x118)
#define ROCEE_OOOA_CFG_AM_CURR_MAX_WR_LATENCY_REG \
				(ROCEE_OOOA_CFG_BASE + 0x130)
#define ROCEE_OOOA_CFG_AM_CURR_AVA_WR_LATENCY_REG \
				(ROCEE_OOOA_CFG_BASE + 0x134)
#define ROCEE_OOOA_CFG_AM_CURR_WR_LATENCY_REG \
				(ROCEE_OOOA_CFG_BASE + 0x138)

#define ROCEE_OOOA_CFG_AM_CURR_RD_TXID_STS_L_REG \
				(ROCEE_OOOA_CFG_BASE + 0x160)
#define ROCEE_OOOA_CFG_AM_CURR_RD_TXID_STS_H_REG \
				(ROCEE_OOOA_CFG_BASE + 0x164)
#define ROCEE_OOOA_CFG_AM_CURR_WR_TXID_STS_L_REG \
				(ROCEE_OOOA_CFG_BASE + 0x170)
#define ROCEE_OOOA_CFG_AM_CURR_WR_TXID_STS_H_REG \
				(ROCEE_OOOA_CFG_BASE + 0x174)
#define ROCEE_OOOA_CFG_AM_ALARM_RRESP_REG \
				(ROCEE_OOOA_CFG_BASE + 0x180)
#define ROCEE_OOOA_CFG_AM_ALARM_BRESP_REG \
				(ROCEE_OOOA_CFG_BASE + 0x184)

#define ROCEE_OOOB_CFG_AM_CTRL_GLOBAL_REG \
				(ROCEE_OOOB_CFG_BASE + 0x0)
#define ROCEE_OOOB_CFG_AM_CTRL_LATENCY_SEL_REG \
				(ROCEE_OOOB_CFG_BASE + 0x4)
#define ROCEE_OOOB_CFG_AM_CFG_MAX_TRANS_REG \
				(ROCEE_OOOB_CFG_BASE + 0x10)
#define ROCEE_OOOB_CFG_AM_CFG_SINGLE_PORT_MAX_TRANS_REG \
				(ROCEE_OOOB_CFG_BASE + 0x14)

#define ROCEE_OOOB_CFG_AM_CURR_PORT_STS_REG \
				(ROCEE_OOOB_CFG_BASE + 0x100)
#define ROCEE_OOOB_CFG_AM_CURR_ROB_ECC_ERR_REG \
				(ROCEE_OOOB_CFG_BASE + 0x10C)
#define ROCEE_OOOB_CFG_AM_CURR_MAX_RD_LATENCY_REG \
				(ROCEE_OOOB_CFG_BASE + 0x110)
#define ROCEE_OOOB_CFG_AM_CURR_AVA_RD_LATENCY_REG \
				(ROCEE_OOOB_CFG_BASE + 0x114)
#define ROCEE_OOOB_CFG_AM_CURR_RD_LATENCY_REG \
				(ROCEE_OOOB_CFG_BASE + 0x118)
#define ROCEE_OOOB_CFG_AM_CURR_MAX_WR_LATENCY_REG \
				(ROCEE_OOOB_CFG_BASE + 0x130)
#define ROCEE_OOOB_CFG_AM_CURR_AVA_WR_LATENCY_REG \
				(ROCEE_OOOB_CFG_BASE + 0x134)
#define ROCEE_OOOB_CFG_AM_CURR_WR_LATENCY_REG \
				(ROCEE_OOOB_CFG_BASE + 0x138)

#define ROCEE_OOOB_CFG_AM_CURR_RD_TXID_STS_L_REG \
				(ROCEE_OOOB_CFG_BASE + 0x160)
#define ROCEE_OOOB_CFG_AM_CURR_RD_TXID_STS_H_REG \
				(ROCEE_OOOB_CFG_BASE + 0x164)
#define ROCEE_OOOB_CFG_AM_CURR_WR_TXID_STS_L_REG \
				(ROCEE_OOOB_CFG_BASE + 0x170)
#define ROCEE_OOOB_CFG_AM_CURR_WR_TXID_STS_H_REG \
				(ROCEE_OOOB_CFG_BASE + 0x174)
#define ROCEE_OOOB_CFG_AM_ALARM_RRESP_REG \
				(ROCEE_OOOB_CFG_BASE + 0x180)
#define ROCEE_OOOB_CFG_AM_ALARM_BRESP_REG \
				(ROCEE_OOOB_CFG_BASE + 0x184)

#endif /* _HNS_ROCE_COMMON_H */
