imx-camera-objs := imx-camif.o imx-ic-prpenc.o imx-of.o \
		imx-smfc.o imx-vdic.o

obj-$(CONFIG_VIDEO_IMX_CAMERA) += imx-camera.o
obj-$(CONFIG_VIDEO_IMX_CAMERA) += imx-csi.o
obj-$(CONFIG_IMX_MIPI_CSI2) += mipi-csi2.o
obj-$(CONFIG_IMX_VIDEO_SWITCH) += imx-video-switch.o
obj-$(CONFIG_IMX_CAMERA_OV5640_MIPI) += ov5640-mipi.o
obj-$(CONFIG_IMX_CAMERA_OV5642) += ov5642.o
