snd-fireface-objs := fireface.o fireface-transaction.o fireface-midi.o \
		     fireface-proc.o amdtp-ff.o fireface-stream.o \
		     fireface-pcm.o fireface-hwdep.o
obj-$(CONFIG_SND_FIREFACE) += snd-fireface.o
