# Synchronous hardware clients (Intel/AMD)
obj-$(CONFIG_NTB_PINGPONG) += ntb_pingpong.o
obj-$(CONFIG_NTB_TOOL)     += ntb_tool.o
obj-$(CONFIG_NTB_PERF)     += ntb_perf.o
# Asynchronous hardware clients (IDT)
obj-$(CONFIG_NTB_DB_TEST)  += ntb_db_test.o
obj-$(CONFIG_NTB_MSG_TEST) += ntb_msg_test.o
obj-$(CONFIG_NTB_MW_TEST)  += ntb_mw_test.o
