obj-y += \
    venc_drv_if.o

ccflags-y += \
    -I$(srctree)/include/ \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/include \
    -I$(srctree)/drivers/media/platform/mtk-vpu