obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += venc_vp8_if.o venc_vp8_vpu.o

ccflags-y += \
    -I$(srctree)/include/ \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/ \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/include \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/vp8_enc \
    -I$(srctree)/drivers/media/platform/mtk-vpu
